### ISSUE TITLE
pipenv --three install produces correct results where --two does not

### ISSUE THREAD

**Issue by caseywebdev** [pypa/pipenv#1522]
Be sure to check the existing issues, both open and closed.

Describe the issue briefly here.

##### Describe your environment

1. Linux
1. Python version: `3.6.4` and `2.7.9`
1. Pipenv version: `11.10.0`

##### Expected result

I expected the wtforms package contents to be correct.

##### Actual result

It appears the wtforms package contents was the latest version overridden by the specified version.

##### Steps to replicate

This is easiest to replicate with docker where the environment is clean:

```sh
docker run -it --rm python bash

pip install pipenv==11.10.0

export PIPENV_VENV_IN_PROJECT=1

# Test python3
mkdir /test-python3 && cd /test-python3
pipenv install --three wtforms==1.0.5

# Notice files line up with wtforms==1.0.5
# (https://pypi.python.org/packages/fb/9d/9dcdb7a9a19301c0cc04eca1aa8c60da50d97156f3c10e24519eb77202e1/WTForms-1.0.5.zip)
ls -la .venv/lib/python3.6/site-packages/wtforms/

# Test python2
mkdir /test-python2 && cd /test-python2
pipenv install --two wtforms==1.0.5

# Notice it appears the files from wtforms==2.1
# (https://pypi.python.org/packages/bf/91/2e553b86c55e9cf2f33265de50e052441fb753af46f5f20477fe9c61280e/WTForms-2.1.zip)
# were overriden by the files from wtforms==1.0.5
ls -la .venv/lib/python2.7/site-packages/wtforms/
```

**Comment by caseywebdev** [comment]
I'm still seeing the same issue with `pipenv@11.8.3`. Can you explain why you closed the issue?

**Comment by techalchemy** [comment]
This is fixed in master via #1854

**Comment by caseywebdev** [comment]
I'm still seeing the same result in `11.10.0`. Are you seeing the correct package contents for python2 in my example on `11.10.0`? I've updated the pipenv version in the example so it's a simple copy/paste and visual comparison on the `ls` output.

**Comment by techalchemy** [comment]
I’m guessing this relates to the json api which I thought we disabled...

**Comment by techalchemy** [comment]
I'm actually going to close this in favor of #1952 for now since I think it's captured a bit more clearly there
