### ISSUE TITLE
Pipenv lock fails to resolve dependencies

### ISSUE THREAD

**Issue by scmmmh** [pypa/pipenv#1579]
Be sure to check the existing issues, both open and closed.

Running `pipenv lock` fails to resolve the dependencies and generate a Pipfile.lock, producing the error listed below.

Running `pipenv install --skip-lock` works fine and as the output below shows pipenv has tried the version (3.0.0b7) that matches the requirement. There is no other dependency on marshmallow. Also `pipenv install` runs fine if the virtualenv is first removed with `pipenv --rm`.

##### Describe your environment

1. OS Type - Ubuntu 17.10
1. Python version: 3.6.2
1. Pipenv version: 11.0.2

##### Expected result

A Pipfile.lock is generated

##### Actual result

```
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
Could not find a version that matches marshmallow>=3.0.0b7
Tried: 0.1.0, 0.1.0, 0.2.0, 0.2.0, 0.2.1, 0.2.1, 0.3.0, 0.3.0, 0.3.1, 0.3.1, 0.4.0, 0.4.0, 0.4.1, 0.4.1, 0.5.0, 0.5.0, 0.5.1, 0.5.1, 0.5.2, 0.5.2, 0.5.3, 0.5.3, 0.5.4, 0.5.4, 0.5.5, 0.5.5, 0.6.0, 0.6.0, 0.7.0, 0.7.0, 1.0.0a0, 1.0.0a0, 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.2.1, 1.2.1, 1.2.2, 1.2.2, 1.2.3, 1.2.3, 1.2.4, 1.2.4, 1.2.5, 1.2.5, 1.2.6, 1.2.6, 2.0.0a1, 2.0.0a1, 2.0.0b1, 2.0.0b1, 2.0.0b2, 2.0.0b2, 2.0.0b3, 2.0.0b3, 2.0.0b4, 2.0.0b4, 2.0.0b5, 2.0.0b5, 2.0.0rc1, 2.0.0rc1, 2.0.0rc2, 2.0.0rc2, 2.0.0, 2.0.0, 2.1.0, 2.1.0, 2.1.1, 2.1.1, 2.1.2, 2.1.2, 2.1.3, 2.1.3, 2.2.0, 2.2.0, 2.2.1, 2.2.1, 2.3.0, 2.3.0, 2.4.0, 2.4.0, 2.4.1, 2.4.1, 2.4.2, 2.4.2, 2.5.0, 2.5.0, 2.6.0, 2.6.0, 2.6.1, 2.6.1, 2.7.0, 2.7.0, 2.7.1, 2.7.2, 2.7.2, 2.7.3, 2.7.3, 2.8.0, 2.8.0, 2.9.0, 2.9.0, 2.9.1, 2.9.1, 2.10.0, 2.10.0, 2.10.1, 2.10.1, 2.10.2, 2.10.2, 2.10.3, 2.10.3, 2.10.4, 2.10.4, 2.10.5, 2.10.5, 2.11.0, 2.11.0, 2.11.1, 2.11.1, 2.12.0, 2.12.0, 2.12.1, 2.12.1, 2.12.2, 2.12.2, 2.13.0, 2.13.0, 2.13.1, 2.13.1, 2.13.2, 2.13.2, 2.13.3, 2.13.3, 2.13.4, 2.13.4, 2.13.5, 2.13.5, 2.13.6, 2.13.6, 2.14.0, 2.14.0, 2.15.0, 2.15.0, 3.0.0a1, 3.0.0a1, 3.0.0b1, 3.0.0b1, 3.0.0b2, 3.0.0b2, 3.0.0b3, 3.0.0b3, 3.0.0b4, 3.0.0b4, 3.0.0b5, 3.0.0b5, 3.0.0b6, 3.0.0b6, 3.0.0b7, 3.0.0b7
```

This used to work with the 10.0.0 release and started failing after upgrading to 11.0.2.

##### Steps to replicate

I have attached the Pipfile, verbose output from the `pipenv lock`, and the output from `pipenv graph`:

[config_logs.tar.gz](https://github.com/pypa/pipenv/files/1789035/config_logs.tar.gz)

Unpack the file and run
`pipenv install`
`pipenv lock`

**Comment by scmmmh** [comment]
This might be a regression of #965. I have just tested that running `pipenv lock --pre` works. My Pipfile has the necessary allow_prereleases = true setting, so perhaps that is the issue.

**Comment by sheats** [comment]
Oh, and pipenv lock --pre or pipenv install firebase-admin --pre did not work for me.

**Comment by kennethreitz** [comment]
futures seems to have something weird going on in its setup.py

**Comment by j-walker23** [comment]
@kennethreitz futures doesn't show up in the `pipenv graph`. Is there anyway to figure out what depencency cares about `futures`? I am in a py3.6 only env and am not sure why i can't get a `Pipfile.lock`.
Thanks for any help.

**Comment by j-walker23** [comment]
@kennethreitz Could you give a little insight on what you meant by futures setup.py weirdness please? I'm not sure what to put down as the issue that is referenced above.

**Comment by agronholm** [comment]
@kennethreitz care to elaborate? I've made every effort for`futures` to not be installable on Python 3 as it contains Python 2 only syntax.

**Comment by crifan** [comment]
same issue here: `Locking [packages] dependencies...` hang forever
make pipenv not usable now !!!

macOS High Sierra 10.13.6
Python: Python 3.6.4
pipenv: version 2018.7.1

**Comment by BillKG** [comment]
I managed to fix this by deleting the packages from the Pipfile manually by deleting the package under
`[packages]` and then run `pipenv install package-name` again.

**Comment by Echo226** [comment]
> I managed to fix this by deleting the package from the Pipfile manually by removing the package under
> `[packages]` and then run `pipenv install package-name` again.

I fixed this problem with the same method. I'm not sure if it is a good solution but it just works.

**Comment by abooodbah** [comment]
The issue still persists in my case. I have removed firebase-admin manually from the packages list but I still get an issue when running the lock command.

```
ERROR: ERROR: Could not find a version that matches requests<3.0.0,<3.0.0dev,==2.11.1,>=2.0.1,>=2.18.0
Tried: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.6, 0.10.7, 0.10.8, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.14.0, 0.14.1, 0.14.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 2.0.0, 2.0.0, 2.0.1, 2.0.1, 2.1.0, 2.1.0, 2.2.0, 2.2.0, 2.2.1, 2.2.1, 2.3.0, 2.3.0, 2.4.0, 2.4.0, 2.4.1, 2.4.1, 2.4.2, 2.4.2, 2.4.3, 2.4.3, 2.5.0, 2.5.0, 2.5.1, 2.5.1, 2.5.2, 2.5.2, 2.5.3, 2.5.3, 2.6.0, 2.6.0, 2.6.1, 2.6.1, 2.6.2, 2.6.2, 2.7.0, 2.7.0, 2.8.0, 2.8.0, 2.8.1, 2.8.1, 2.9.0, 2.9.0, 2.9.1, 2.9.1, 2.9.2, 2.9.2, 2.10.0, 2.10.0, 2.11.0, 2.11.0, 2.11.1, 2.11.1, 2.12.0, 2.12.0, 2.12.1, 2.12.1, 2.12.2, 2.12.2, 2.12.3, 2.12.3, 2.12.4, 2.12.4, 2.12.5, 2.12.5, 2.13.0, 2.13.0, 2.14.0, 2.14.0, 2.14.1, 2.14.1, 2.14.2, 2.14.2, 2.15.1, 2.15.1, 2.16.0, 2.16.0, 2.16.1, 2.16.1, 2.16.2, 2.16.2, 2.16.3, 2.16.3, 2.16.4, 2.16.4, 2.16.5, 2.16.5, 2.17.0, 2.17.0, 2.17.1, 2.17.1, 2.17.2, 2.17.2, 2.17.3, 2.17.3, 2.18.0, 2.18.0, 2.18.1, 2.18.1, 2.18.2, 2.18.2, 2.18.3, 2.18.3, 2.18.4, 2.18.4, 2.19.0, 2.19.0, 2.19.1, 2.19.1, 2.20.0, 2.20.0, 2.20.1, 2.20.1, 2.21.0, 2.21.0, 2.22.0, 2.22.0, 2.23.0, 2.23.0, 2.24.0, 2.24.0
There are incompatible versions in the resolved dependencies.
```

**Comment by mvincerx** [comment]
I struggled with this one for a while. Then I found what I believe is the root cause of the failure.
I decided to switch over to pipenv after pipreqs failed on my system due to other Python3.8 upgrades.

I ran these commands with an existing requirements.txt file present in working dir:
`python3 -m pipenv install`
[This worked fine]
`python3 -m pipenv lock`
[This failed. And the resolution path given in stdout was not helpful, IMHO]

I decided to look at *how* my existing requirements.txt was parsed and imported in the Pipfile.
As it turns out, I believe there may be a parsing error in pipenv, which might be easily resolved.

So I opened my Pipfile, and I noticed that whereas some dependencies used a general syntax, like so:
```
simple-term-menu = "*"
prompt-toolkit = "*"
```
Other packages (which apparently were parsed by pipenv) retained the origin `==` like so:
```
Sphinx = "==3.0.3"
Pygments = "==2.2.0"
```
Of course, the above syntax didn't look correct to me. So I corrected the syntax, removing the redundant ``==`` like so:
```
Sphinx = "3.0.3"
Pygments = "2.2.0"
```
Then I re-ran the command:
`python3 -m pipenv lock`

And finally, pipenv created a Pipfile.lock successfully.

I hope this helps someone else who converts to using `pipenv` and plans to use an existing requirements.txt.

**Comment by surafelkifetew1** [comment]
try 
pipenv lock --pre

**Comment by spacelord19** [comment]
> 
> 
> I struggled with this one for a while. Then I found what I believe is the root cause of the failure.
> I decided to switch over to pipenv after pipreqs failed on my system due to other Python3.8 upgrades.
> 
> I ran these commands with an existing requirements.txt file present in working dir:
> `python3 -m pipenv install`
> [This worked fine]
> `python3 -m pipenv lock`
> [This failed. And the resolution path given in stdout was not helpful, IMHO]
> 
> I decided to look at _how_ my existing requirements.txt was parsed and imported in the Pipfile.
> As it turns out, I believe there may be a parsing error in pipenv, which might be easily resolved.
> 
> So I opened my Pipfile, and I noticed that whereas some dependencies used a general syntax, like so:
> 
> ```
> simple-term-menu = "*"
> prompt-toolkit = "*"
> ```
> 
> Other packages (which apparently were parsed by pipenv) retained the original `==` like so:
> 
> ```
> Sphinx = "==3.0.3"
> Pygments = "==2.2.0"
> ```
> 
> Of course, the above syntax didn't look correct to me. So I corrected the syntax, removing the redundant `==` like so:
> 
> ```
> Sphinx = "3.0.3"
> Pygments = "2.2.0"
> ```
> 
> Then I re-ran the command:
> `python3 -m pipenv lock`
> 
> And finally, pipenv created a Pipfile.lock successfully.
> 
> I hope this helps someone else who converts to using `pipenv` and plans to use an existing requirements.txt.

This worked, finally. Thanks

**Comment by mvincerx** [comment]
@spacelord19 I'm glad that I could be of help.  😄
