### ISSUE TITLE
VCS install fails

### ISSUE THREAD

**Issue by paradoxxxzero** [pypa/pipenv#1714]
On a clean environment:
```bash
$ pipenv --version
pipenv, version 11.6.3
```
```bash
$ pipenv install -e "git+https://github.com/django/django.git#egg=django"
Creating a virtualenv for this project…
Using /usr/bin/python (3.6.4) to create virtualenv…
⠋Already using interpreter /usr/bin/python
Using base prefix '/usr'
New python executable in /[path]/.local/share/virtualenvs/gittest-YBJVqmXZ/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /[path]/.local/share/virtualenvs/gittest-YBJVqmXZ
Creating a Pipfile for this project…
Installing -e git+https://github.com/django/django.git#egg=django…
Obtaining django from git+https://github.com/django/django.git#egg=django
  Cloning https://github.com/django/django.git to /[path]/.local/share/virtualenvs/gittest-YBJVqmXZ/src/django
Collecting pytz (from django)
  Using cached pytz-2018.3-py2.py3-none-any.whl
Installing collected packages: pytz, django
  Running setup.py develop for django
Successfully installed django pytz-2018.3

Adding -e git+https://github.com/django/django.git#egg=django to Pipfile's [packages]…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
dor/packaging/requirements.py", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip9._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'-i https'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pipenv/resolver.py", line 66, in <module>
    main()
  File "/usr/lib/python3.6/site-packages/pipenv/resolver.py", line 54, in main
    results = resolve(packages, pre=do_pre, sources=project.sources, verbose=is_verbose, clear=do_clear)
  File "/usr/lib/python3.6/site-packages/pipenv/resolver.py", line 52, in resolve
    return pipenv.utils.resolve_deps(packages, which, project=project, pre=pre, sources=sources, clear=clear, verbose=verbose)
  File "/usr/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 397, in resolve_deps
    resolved_tree, resolver = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
  File "/usr/lib/python3.6/site-packages/pipenv/../pipenv/utils.py", line 284, in actually_resolve_reps
    constraint = req.InstallRequirement.from_editable(dep[len('-e '):])
  File "/usr/lib/python3.6/site-packages/pipenv/../pipenv/vendor/pip9/req/req_install.py", line 156, in from_editable
    wheel_cache=wheel_cache)
  File "/usr/lib/python3.6/site-packages/pipenv/../pipenv/vendor/pip9/req/req_install.py", line 91, in __init__
    "Invalid requirement: '%s'\n%s" % (req, add_msg))
pip9.exceptions.InstallationError: Invalid requirement: 'django -i https://pypi.python.org/simple'
It looks like a path. Does it exist ?

```

As far as I can see a `-i https://pypi.python.org/simple` is added to the requirement and isn't correctly parsed by `REQUIREMENT.parseString`

Same thing with `git@github.com:...` urls
Same thing without `-e`

**Comment by kennethreitz** [comment]
fixed in recent releases :)

**Comment by paradoxxxzero** [comment]
Hum I still get exactly the same thing with 11.6.7. Am I missing something?

**Comment by kennethreitz** [comment]
will investigate

**Comment by randycoulman** [comment]
I am also seeing this on 11.6.7.  I'm happy to run commands to help trouble-shoot.

**Comment by kennethreitz** [comment]
will fix :)

**Comment by randycoulman** [comment]
Confirmed fixed for me in 11.6.9.  Thanks!

**Comment by kennethreitz** [comment]
sorry for the :bug:!
