### ISSUE TITLE
pipenv refuses to work with Travis CI?

### ISSUE THREAD

**Issue by kakulukia** [pypa/pipenv#2120]
Pipenv is not installing anything on Travis CI.
It was working until the last job run with pipenv 9.1.0.

------------

##### Expected result

The project requirements should have been installed like they were 2 months ago during the last test build.

##### Actual result

0.50s$ pipenv install --deploy
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead.
Warning: --system is intended to be used for Pipfile installation, not installation of specific packages. Aborting.
See also: --deploy flag.
The command "pipenv install --deploy" failed and exited with 1 during .

Linke seen in the first line im not using the --system flag it is complaining about.
The old command was 'pipenv install --dev' and i tried out the --deploy in the last test, but im not sure what changed and is keeping me from successfully testing my packaged with travis. 
I could manually install an old version i guess, but id like to understand whats wrong here.

##### Steps to replicate

Let pipenv install requirements on Travis CI.

**Comment by sp4ghet** [comment]
I'm also suddenly seeing this new issue pop up.
My understanding is that pipenv --system fails if you attempt to install one package even if you have a Pipfile

**Comment by kakulukia** [comment]
And i neither use --system nor try to install a single package. Do you @sp4ghet?

**Comment by uranusjr** [comment]
I believe this is the same as #2078, and fixed in #2091. Unfortunately this did not make it into the last release, so we’ll have to wait a little…

**Comment by techalchemy** [comment]
Lol. I didn’t realize it fails with only one package also. That sucks. I’ll see if I can get this out today

**Comment by rupav** [comment]
@techalchemy  can you explain more, I have Pipfile with multiple packages, still can't get past through this error.

**Comment by kakulukia** [comment]
pipenv is still broken for me even with the new version :(

**Comment by jwflory** [comment]
I was able to use Travis CI and pipenv together following the advice of [this blog post](https://jollyremedy.wordpress.com/2018/02/07/using-pipenv-in-a-travis-build/ "Using pipenv in a Travis build"):

```yaml
language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv sync'
script: 'python -m pytest --cov=pyblizzard tests --cov-report=xml'
after_success:
  - 'python-codacy-coverage -r coverage.xml'
```

**Comment by kakulukia** [comment]
I switched from pipenv to poetry, since i had multiple occasions like this with pipenv. 
So i cant test this anymore.
