### ISSUE TITLE
The `pipenv install --deploy --system` command is no longer working.

### ISSUE THREAD

**Issue by ryan-blunden** [pypa/pipenv#2183]
Be sure to check the existing issues (both open and closed!).

The `pipenv install --deploy --system` command is no longer working.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.4'`

Pipenv location: `'/usr/local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Other Python installations in `PATH`:

  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `3.6.5`: `/usr/local/bin/python`
  - `3.6.5`: `/usr/local/bin/python`
  - `3.6.5`: `/usr/local/bin/python3`
  - `3.6.5`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.9.87-linuxkit-aufs',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Fri Mar 16 18:16:33 UTC 2018',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `HOSTNAME`
  - `SHLVL`
  - `PYTHON_PIP_VERSION`
  - `HOME`
  - `GPG_KEY`
  - `PATH`
  - `LANG`
  - `PYTHON_VERSION`
  - `PWD`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/usr/src/app`

---------------------------

Contents of `Pipfile` ('/usr/src/app/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
records = "*"

[dev-packages]

[requires]
python_version = "3.6"

```

</details>

------------

##### Expected result

The `pipenv install --deploy --system` command completes successfully.

##### Actual result

Command exists with code 1 with the following output.

```
+ pipenv install --deploy --system
Warning: --system is intended to be used for Pipfile installation, not installation of specific packages. Aborting.
See also: --deploy flag.
```

##### Steps to replicate

See the gist at https://gist.github.com/ryan-blunden/e27f8e48b134e041be22f07fcac943de and run `make build.

**Comment by nhamlh** [comment]
It's required that the Pipfile.lock presents in the current folder for the `--system` option to work.

**Comment by uranusjr** [comment]
We can probably improve the error message to let the user know what to do next.

**Comment by ryan-blunden** [comment]
That would be great.

What exactly is the problem with that command now? Is there still a way to
install libraries globally?

**Comment by uranusjr** [comment]
@ryan-blunden I didn’t check but #2181 could help.

**Comment by skorokithakis** [comment]
I got the same error trying to run `pipenv --install`. Shouldn't it have created the lockfile itself, instead of give an error?

**Comment by stardust85** [comment]
With `--deploy` command you should definitely have Pipfile.lock and you whould have it up-to-date. However the error message it gives should mention this. Without `--deploy` I'm not sure if it should require running `pipenv lock` explicitly.

**Comment by skorokithakis** [comment]
In my case, I'm using neither `--deploy` nor `--system`. Pipenv just seems to think I am.

**Comment by techalchemy** [comment]
Fixed by #2181

**Comment by ryan-blunden** [comment]
Many thanks!

**Comment by ryan-blunden** [comment]
Hi @techalchemy,

This needs to be re-opened as `pipenv install --deploy --system` is still failing.

Tested just now with pipenv version `pipenv-2018.5.18`.

**Comment by ryan-blunden** [comment]
I tried changing the command just to `pipenv install --system` but that didn't work either.

`
+ pipenv install --system
Warning: --system is intended to be used for Pipfile installation, not installation of specific packages. Aborting.
See also: --deploy flag.
`

I'm using https://gist.github.com/ryan-blunden/e27f8e48b134e041be22f07fcac943de to test.

**Comment by techalchemy** [comment]
Hi @ryan-blunden. The Issue tracker is used for tracking changes merged into master. We already read your issue and fixed it in master, please do not use this as a forum to tell us how to run the project.

**Comment by ryan-blunden** [comment]
@techalchemy,

My apologies, that's not what I was trying to do. 

I changed my gist to install pipenv from master but I'm still getting the same error message.

Have I missed something? Is there a new way I tell pipenv to install system packages?

**Comment by uranusjr** [comment]
@ryan-blunden I think this has been fixed, and will be released soon. Please wait a few days to see if there is a new version, and open an issue if it is not fixed by then.

**Comment by ryan-blunden** [comment]
Ok, thanks @uranusjr. Will do.

**Comment by techalchemy** [comment]
@ryan-blunden with the gist you linked, you should be getting an error, but it seems like you're getting the _wrong_ error.  If you are passing `--system` you can't install from a pipfile, you _must_ have a lockfile unless you pass `--skip-lock`.  If you pass `--deploy` you can't install from an out-of-date lockfile (one that is out of sync with your pipfile) which means you must both include your pipfile AND your lockfile and they must be in sync.

If you want to do the resolution step in a container you need to drop the `--deploy` flag and add the `--site-packages` flag.

**Comment by TwoBitAlchemist** [comment]
:wave: Hi from 2020. I found this on Google and encountered this same misleading error. The problem was indeed a missing `Pipfile.lock`. Is there somewhere clearer I can +1 prioritizing the work to improve the error in this case? Cheers!

**Comment by uranusjr** [comment]
I don’t think there is one. Pipenv is entirely volunteer work, so the only way to prioritise something is to do it yourself (or sponsor someone to specifically do it).
