### ISSUE TITLE
Calling 'graph' argument breaks pipenv

### ISSUE THREAD

**Issue by vvcorto** [pypa/pipenv#2978]
### Issue description

Calling the `graph` argument in pipenv makes the tool break

### Expected result

Display the actual project dependencies

### Actual result

```
/Users/<myuser>/Library/Python/2.7/bin/pipenv graph --json
    Traceback (most recent call last):
      File "/Users/<myuser>/Library/Python/2.7/bin/pipenv", line 11, in <module>
        sys.exit(cli())
      File "/Users/<myuser>/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/Users/<myuser>/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/Users/<myuser>/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/Users/<myuser>/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/Users/<myuser>/Library/Python/2.7/lib/python/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/Users/<myuser>/Library/Python/2.7/lib/python/site-packages/pipenv/cli/command.py", line 528, in graph
        do_graph(bare=bare, json=json, json_tree=json_tree, reverse=reverse)
      File "/Users/<myuser>/Library/Python/2.7/lib/python/site-packages/pipenv/core.py", line 2397, in do_graph
        for d in simplejson.loads(c.out):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
        return _default_decoder.decode(s)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded
```

### Steps to replicate

Provide the steps to replicate (which usually at least includes the commands and the Pipfile).

Run `/Users/<myuser>/Library/Python/2.7/bin/pipenv graph --json` on MacOS High Sierra

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.10.9'`

Pipenv location: `'/Users/<myuser>/Library/Python/2.7/lib/python/site-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:

  - `2.7.10`: `/usr/bin/python`
  - `2.7.15`: `/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/bin/python2.7`
  - `2.7.10`: `/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7`
  - `3.7.0`: `/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/bin/python3.7`
  - `2.7.10`: `/usr/bin/pythonw`
  - `3.7.0`: `/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/bin/python3.7m`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64',
 'python_full_version': '2.7.10',
 'python_version': '2.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `ZPLUG_USE_CACHE`
  - `_ZPLUG_AWKPATH`
  - `LESS`
  - `ZPLUG_ROOT`
  - `LC_CTYPE`
  - `TERM_PROGRAM_VERSION`
  - `ZPLUG_HOME`
  - `LOGNAME`
  - `USER`
  - `PATH`
  - `HOME`
  - `ZPLUG_FILTER`
  - `ZSH`
  - `DISPLAY`
  - `TERM_PROGRAM`
  - `LANG`
  - `TERM`
  - `Apple_PubSub_Socket_Render`
  - `COLORFGBG`
  - `_ZPLUG_CONFIG_SUBSHELL`
  - `SHLVL`
  - `SECURITYSESSIONID`
  - `ZPLUG_THREADS`
  - `XPC_FLAGS`
  - `ITERM_SESSION_ID`
  - `_ZPLUG_URL`
  - `_`
  - `_ZPLUG_OHMYZSH`
  - `ZPLUG_REPOS`
  - `TERM_SESSION_ID`
  - `XPC_SERVICE_NAME`
  - `VERSIONER_PYTHON_PREFER_32_BIT`
  - `PIP_SHIMS_BASE_MODULE`
  - `SSH_AUTH_SOCK`
  - `PERIOD`
  - `FPATH`
  - `SHELL`
  - `PYTHONDONTWRITEBYTECODE`
  - `ITERM_PROFILE`
  - `PIP_PYTHON_PATH`
  - `ZPLUG_PROTOCOL`
  - `TMPDIR`
  - `ZPLUG_CACHE_DIR`
  - `LSCOLORS`
  - `AUTOJUMP_SOURCED`
  - `ZPLUG_LOADFILE`
  - `OLDPWD`
  - `VERSIONER_PYTHON_VERSION`
  - `ZPLUG_ERROR_LOG`
  - `__CF_USER_TEXT_ENCODING`
  - `ZPLUG_BIN`
  - `PWD`
  - `AUTOJUMP_ERROR_PATH`
  - `COLORTERM`
  - `_ZPLUG_PREZTO`
  - `_ZPLUG_VERSION`
  - `PAGER`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/zplug/2.4.2/bin:/Users/<myuser>/Library/Python/2.7/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/<myuser>/.oh-my-zsh/custom/plugins/noreallyjustfuckingstopalready`
  - `SHELL`: `/usr/local/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/<myuser>/Dropbox (Personal)/dev/python-projects/daft-lookout`

---------------------------

Contents of `Pipfile` ('/Users/<myuser>/Dropbox (Personal)/dev/python-projects/daft-lookout/Pipfile'):

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[dev-packages]

[packages]
daftlistings = "*"
"html2text" = "*"

[requires]
python_version = "2.7"

```

Contents of `Pipfile.lock` ('/Users/<myuser>/Dropbox (Personal)/dev/python-projects/daft-lookout/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "d06dff9fd1c955d4fe438452e71baabc926c6c268a505839f9688a530a60f017"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "2.7"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "beautifulsoup4": {
            "hashes": [
                "sha256:194ec62a25438adcb3fdb06378b26559eda1ea8a747367d34c33cef9c7f48d57",
                "sha256:90f8e61121d6ae58362ce3bed8cd997efb00c914eae0ff3d363c32f9a9822d10",
                "sha256:f0abd31228055d698bb392a826528ea08ebb9959e6bea17c606fd9c9009db938"
            ],
            "version": "==4.6.3"
        },
        "certifi": {
            "hashes": [
                "sha256:376690d6f16d32f9d1fe8932551d80b23e9d393a8578c5633a2ed39a64861638",
                "sha256:456048c7e371c089d0a77a5212fb37a2c2dce1e24146e3b7e0261736aaeaa22a"
            ],
            "version": "==2018.8.24"
        },
        "chardet": {
            "hashes": [
                "sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae",
                "sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691"
            ],
            "version": "==3.0.4"
        },
        "daftlistings": {
            "hashes": [
                "sha256:52c6886dff0ebc96278365f939808fc71cde55960be2abac737ac6f62b18eadc",
                "sha256:e9e73d759ddd738b527e75e719c2f4f6578853ecb6810061b0e412f72a63ae41"
            ],
            "index": "pypi",
            "version": "==1.6.2"
        },
        "enum34": {
            "hashes": [
                "sha256:2d81cbbe0e73112bdfe6ef8576f2238f2ba27dd0d55752a776c41d38b7da2850",
                "sha256:644837f692e5f550741432dd3f223bbb9852018674981b1664e5dc339387588a",
                "sha256:6bd0f6ad48ec2aa117d3d141940d484deccda84d4fcd884f5c3d93c23ecd8c79",
                "sha256:8ad8c4783bf61ded74527bffb48ed9b54166685e4230386a9ed9b1279e2df5b1"
            ],
            "version": "==1.1.6"
        },
        "html2text": {
            "hashes": [
                "sha256:490db40fe5b2cd79c461cf56be4d39eb8ca68191ae41ba3ba79f6cb05b7dd662",
                "sha256:627514fb30e7566b37be6900df26c2c78a030cc9e6211bda604d8181233bcdd4"
            ],
            "index": "pypi",
            "version": "==2018.1.9"
        },
        "idna": {
            "hashes": [
                "sha256:156a6814fb5ac1fc6850fb002e0852d56c0c8d2531923a51032d1b70760e186e",
                "sha256:684a38a6f903c1d71d6d5fac066b58d7768af4de2b832e426ec79c30daa94a16"
            ],
            "version": "==2.7"
        },
        "requests": {
            "hashes": [
                "sha256:63b52e3c866428a224f97cab011de738c36aec0185aa91cfacd418b5d58911d1",
                "sha256:ec22d826a36ed72a7358ff3fe56cbd4ba69dd7a6718ffd450ff0e9df7a47ce6a"
            ],
            "version": "==2.19.1"
        },
        "urllib3": {
            "hashes": [
                "sha256:a68ac5e15e76e7e5dd2b8f94007233e01effe3e50e8daddf69acfd81cb686baf",
                "sha256:b5725a0bd4ba422ab0e66e89e030c806576753ea3ee08554382c14e685d117b5"
            ],
            "version": "==1.23"
        }
    },
    "develop": {}
}

```
</details>

**Comment by mhadam** [comment]
I found this happen in the pipenv integration in PyCharm as well.

**Comment by techalchemy** [comment]
This is fixed in master and we are working with the pycharm folks on cutting the next release asap

Sorry for the issue nad thanks for your patience

**Comment by vlad-telnyx** [comment]
Hi,

So how exactly do I update to 'master' ? Installing pipenv via pip doesn't fix the issue as it thinks there's no update...

**Comment by jnns** [comment]
pip supports installing packages from version control: 

    pip install --user git+https://github.com/pypa/pipenv.git@master
