### ISSUE TITLE
Pyenv support broken

### ISSUE THREAD

**Issue by Nothing4You** [pypa/pipenv#3551]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Pipenv.

```
$ pipenv --version
pipenv, version 2018.11.26
```

Probably related to #3136, however, I can't reopen that.

### Issue description

pipenv doesn't find pyenv-python versions.

### Expected result

When calling `pipenv install` pipenv should detect existing versions of Python installed by pyenv. If it doesn't find a Python version as specified in the Pipfile it should start installing the correct Python version via pyenv and then use it to create the virtual environment.

### Actual result / Steps to replicate

```
$ pyenv versions
* system (set by /Users/$USER/.pyenv/version)
  3.5.5
  3.6.5
  3.6.8
$ env|grep PY
PYENV_ROOT=/Users/$USER/.pyenv
$ pipenv --python 3.6
Warning: Python 3.6 was not found on your system…
Would you like us to install CPython 3.6.8 with pyenv? [Y/n]:
Installing CPython 3.6.8 with pyenv (this may take a few minutes)…
✔ Success!

Warning: The Python you just installed is not available on your PATH, apparently.
```

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/usr/local/Cellar/pipenv/2018.11.26_2/libexec/lib/python3.7/site-packages/pipenv'`

Python location: `'/usr/local/Cellar/pipenv/2018.11.26_2/libexec/bin/python3.7'`

Python installations found:

  - `3.7.2`: `/usr/local/bin/python3`
  - `3.7.2`: `/usr/local/bin/python3.7m`
  - `2.7.15`: `/usr/local/bin/python`
  - `2.7.15`: `/usr/local/bin/pythonw`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.10`: `/usr/bin/pythonw`
  - `2.7.10`: `/usr/bin/python2.7`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.7.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '18.2.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST '
                     '2018; root:xnu-4903.241.1~1/RELEASE_X86_64',
 'python_full_version': '3.7.2',
 'python_version': '3.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `PATH`
  - `TERM_PROGRAM`
  - `DOTNET_CLI_TELEMETRY_OPTOUT`
  - `PYENV_ROOT`
  - `SHELL`
  - `TERM`
  - `HISTSIZE`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `LC_ALL`
  - `OBJC_DISABLE_INITIALIZE_FORK_SAFETY`
  - `USER`
  - `HISTFILESIZE`
  - `COMMAND_MODE`
  - `SSH_AUTH_SOCK`
  - `__CF_USER_TEXT_ENCODING`
  - `_`
  - `PWD`
  - `LANG`
  - `ITERM_PROFILE`
  - `XPC_FLAGS`
  - `ITERM_ORIG_PS1`
  - `XPC_SERVICE_NAME`
  - `HISTCONTROL`
  - `COLORFGBG`
  - `HOME`
  - `SHLVL`
  - `ITERM_PREV_PS1`
  - `ITERM_SESSION_ID`
  - `LOGNAME`
  - `LC_CTYPE`
  - `SECURITYSESSIONID`
  - `COLORTERM`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_SHIMS_BASE_MODULE`
  - `PIP_PYTHON_PATH`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/Cellar/pipenv/2018.11.26_2/libexec/tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/sbin:/usr/local/opt/go/libexec/bin:/Users/$USER/go/bin:/Users/$USER/.gem/ruby/2.3.0/bin/`
  - `SHELL`: `/bin/bash`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/$USER/dev/myproject`

---------------------------

Contents of `Pipfile` ('/Users/$USER/dev/myproject/Pipfile'):

```toml

```

</details>

**Comment by eng1nerd** [comment]
@Nothing4You  Same problem. You can use specific version of Python you have installed `pipenv --python /Users/$USER/.pyenv/shims/python3.6 install` (you need to specify absolute path to python) before releasing a new version of pipenv.

**Comment by mfisher87** [comment]
I've rolled back from 2018.11.26 to 2018.7.1 to get around this, I don't think the fix is released yet.

**Comment by DaneGrinder** [comment]
I have the same issue here today.

Is the solution, for now, to roll back to 2018.7.1?

**Comment by techalchemy** [comment]
this is resolved in master

you can fix it for now by running `pip install -e git+https://github.com/pypa/pipenv.git@master#egg=pipenv`

sorry for the frustration and thanks for your patience

**Comment by nfplatzke** [comment]
I have tried to use the version in master and it is still failing. This is a clean install on a new box:

[ec2-user@ip-172-23-92-180 gp_audit]$ pipenv --version
pipenv, version 2018.11.27.dev0
[ec2-user@ip-172-23-92-180 gp_audit]$ pyenv --version
pyenv 1.2.11
[ec2-user@ip-172-23-92-180 gp_audit]$ pipenv install
Creating a virtualenv for this project...
Pipfile: /home/ec2-user/jenkins/workspace/reports/report-gp-weekly-status-scan/audit/gp_audit/Pipfile
Using /usr/bin/python2.7 (2.7.14) to create virtualenv...
⠏ Creating virtual environment...  No LICENSE.txt / LICENSE found in source
New python executable in /home/ec2-user/.local/share/virtualenvs/gp_audit-wSTeOHui/bin/python2.7
Also creating executable in /home/ec2-user/.local/share/virtualenvs/gp_audit-wSTeOHui/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/bin/python2.7

✔ Successfully created virtual environment!
Virtualenv location: /home/ec2-user/.local/share/virtualenvs/gp_audit-wSTeOHui
Warning: Your Pipfile requires python_version 3.6, but you are using 2.7.14 (/home/e/.local/share/v/g/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Installing dependencies from Pipfile.lock (f718cf)...

**Comment by pecigonzalo** [comment]
Was this released on a versioned release?

**Comment by Nothing4You** [comment]
@pecigonzalo there hasn't been a release for almost a year, last release was 2018.11.26, so this is still not fixed in a versioned release.

**Comment by Nothing4You** [comment]
See #3742
