### ISSUE TITLE
Git/ssh shorthand not working as documented

### ISSUE THREAD

**Issue by pgorczak** [pypa/pipenv#3663]
### Issue description

The docs on [VCS dependencies](https://github.com/pypa/pipenv/blob/master/docs/basics.rst#-a-note-about-vcs-dependencies) mention a shortcut for git/ssh URLS which doesn't work (but there's a workaround below):

    git+git@<location>:<user_or_organization>/<repository>@<branch_or_tag>#<package_name>

#### URL as documented fails

```
pipenv install -e git+git@github.com:pgorczak/pip-test-package.git@master#piptestpackage
```

```
Installing -e git+git@github.com:pgorczak/pip-test-package.git@master#piptestpackage…
WARNING: pipenv requires an #egg fragment for version controlled dependencies. Please install remote dependency in the form git+git@github.com:pgorczak/pip-test-package.git#egg=<package-name>.
✘ Installation Failed 
```

#### Using fragment as mentioned in the warning hint still fails to lock

```
pipenv install -e git+git@github.com:pgorczak/pip-test-package.git#egg=piptestpackage
```

```
Installing -e git+git@github.com:pgorczak/pip-test-package.git#egg=piptestpackage…
Adding piptestpackage to Pipfile's [packages]…
✔ Installation Succeeded 
Pipfile.lock (1c33a8) out of date, updating to (041216)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
⠋ Pinning VCS Packages...ssh: Could not resolve hostname github.com:pgorczak: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

<details><summary><code>Traceback (most recent call last):</code></summary><pre>
  File "/home/philipp/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/core.py", line 1992, in do_install
    skip_lock=skip_lock,
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/core.py", line 1221, in do_init
    pypi_mirror=pypi_mirror,
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/core.py", line 1068, in do_lock
    lockfile=lockfile
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/utils.py", line 626, in venv_resolve_deps
    dev=dev,
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/utils.py", line 1311, in get_vcs_deps
    with locked_repository(requirement) as repo:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/utils.py", line 1447, in locked_repository
    with requirement.req.locked_vcs_repo(src_dir=src_dir) as repo:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 840, in locked_vcs_repo
    vcsrepo = self.get_vcs_repo(src_dir=src_dir)
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 802, in get_vcs_repo
    vcsrepo.obtain()
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/vcs.py", line 37, in obtain
    self.repo_instance.obtain(self.checkout_directory)
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/vcs/__init__.py", line 332, in obtain
    self.fetch_new(dest, url, rev_options)
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/vcs/git.py", line 198, in fetch_new
    self.run_command(['clone', '-q', url, dest])
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/vcs/__init__.py", line 456, in run_command
    spinner=spinner)
  File "/home/philipp/.local/lib/python3.6/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "git clone -q ssh://git@github.com:pgorczak/pip-test-package.git /tmp/requirementslibn6j93d7z/piptestpackage" failed with error code 128 in None
</pre></details>

#### Workaround

Found in #2704.

It works after replacing the colon before user with a slash, so the working shorthand would be

    git+git@<location>/<user_or_organization>/<repository>@<branch_or_tag>#egg=<package_name>

Successful command:

```
pipenv install -e git+git@github.com/pgorczak/pip-test-package.git#egg=piptestpackage
```

### Steps to replicate

* fork [pip-test-package]
* setup github [ssh access](https://help.github.com/en/articles/connecting-to-github-with-ssh)
* run the commands above (replace my username with yours)

[pip-test-package]: https://github.com/pypa/pip-test-package

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.26'`

Pipenv location: `'/home/philipp/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Python installations found:

  - `3.7.1`: `/usr/bin/python3.7`
  - `3.7.1`: `/usr/bin/python3.7m`
  - `3.6.7`: `/usr/bin/python3`
  - `3.6.7`: `/usr/bin/python3.6m`
  - `2.7.15rc1`: `/usr/bin/python2`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.7',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.0-46-generic',
 'platform_system': 'Linux',
 'platform_version': '#49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019',
 'python_full_version': '3.6.7',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```
</details>

**Comment by frostming** [comment]
This is resolved in master branch, thanks for that.

**Comment by fbenavides69** [comment]
Issue is not solved, when doing: pipenv install  OR pipenv install -r requirements.txt
and the given requirements.txt file contains:
-e git+git@ssh.dev.azure.com:v3/SOME/Other/thing#egg=anything

:v3/ is not correctly processed and in Pipfile so when pipenv starts pulling in the dependcies and it arrives to the given line, it crashes!

I had to manually set the Pipfile correctly so that it would work:
anything = {editable = true,git = "git@ssh.dev.azure.com/v3/SOME/Other/Anything"}

Ubuntu 18.04 (latest patches and all!)
pip install --upgrade pip
Python 3.7.4
pipenv, version 2018.11.26

pipenv installed via:
sudo python3 -m pip install pipenv
