### ISSUE TITLE
 FileNotFoundError: [Errno 2] when installing pipenv from pipfile

### ISSUE THREAD

**Issue by limkin092** [pypa/pipenv#5075]
Hi all, 

I am experiencing some issues while building my docker file on the last shown step (1):

```
COPY Pipfile* ./
RUN pip3 install pipenv
(1) RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy --clear --keep-outdated.
```
I get the following Stacktrace:
```
 > [builder-image 5/5] RUN pipenv install --deploy --clear --keep-outdated:                                                                                                                                                    
#10 1.527 Creating a virtualenv for this project...                                                                                                                                                                            
#10 1.527 Pipfile: /Pipfile                                                                                                                                                                                                    
#10 1.543 Using /usr/bin/python3 (3.10.4) to create virtualenv...                                                                                                                                                              
⠼ Creating virtual environment...created virtual environment CPython3.10.4.final.0-64 in 491ms                                                                                                                                 
#10 2.680   creator CPython3Posix(dest=/.venv, clear=False, no_vcs_ignore=False, global=False)
#10 2.680   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
#10 2.680     added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.37.1
#10 2.680   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
#10 2.680 
#10 2.758✔ Successfully created virtual environment! 
#10 2.760 Traceback (most recent call last):
#10 2.760   File "/usr/local/bin/pipenv", line 8, in <module>
#10 2.760     sys.exit(cli())
#10 2.760   File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 1128, in __call__
#10 2.761     return self.main(*args, **kwargs)
#10 2.761   File "/usr/local/lib/python3.10/dist-packages/pipenv/cli/options.py", line 56, in main
#10 2.761     return super().main(*args, **kwargs, windows_expand_args=False)
#10 2.761   File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 1053, in main
#10 2.761     rv = self.invoke(ctx)
#10 2.761   File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 1659, in invoke
#10 2.762     return _process_result(sub_ctx.command.invoke(sub_ctx))
#10 2.764   File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 1395, in invoke
#10 2.765     return ctx.invoke(self.callback, **ctx.params)
#10 2.765   File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 754, in invoke
#10 2.765     return __callback(*args, **kwargs)
#10 2.766   File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
#10 2.766     return ctx.invoke(f, obj, *args, **kwargs)
#10 2.766   File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 754, in invoke
#10 2.767     return __callback(*args, **kwargs)
#10 2.767   File "/usr/local/lib/python3.10/dist-packages/pipenv/cli/command.py", line 222, in install
#10 2.767     do_install(
#10 2.767   File "/usr/local/lib/python3.10/dist-packages/pipenv/core.py", line 1964, in do_install
#10 2.768     ensure_project(
#10 2.768   File "/usr/local/lib/python3.10/dist-packages/pipenv/core.py", line 552, in ensure_project
#10 2.770     ensure_virtualenv(
#10 2.770   File "/usr/local/lib/python3.10/dist-packages/pipenv/core.py", line 485, in ensure_virtualenv
#10 2.770     do_create_virtualenv(
#10 2.770   File "/usr/local/lib/python3.10/dist-packages/pipenv/core.py", line 1012, in do_create_virtualenv
#10 2.771     project._environment = Environment(
#10 2.772   File "/usr/local/lib/python3.10/dist-packages/pipenv/environment.py", line 70, in __init__
#10 2.772     self._base_paths = self.get_paths()
#10 2.773   File "/usr/local/lib/python3.10/dist-packages/pipenv/environment.py", line 394, in get_paths
#10 2.774     c = subprocess_run(command)
#10 2.774   File "/usr/local/lib/python3.10/dist-packages/pipenv/utils/processes.py", line 75, in subprocess_run
#10 2.774     return subprocess.run(
#10 2.775   File "/usr/lib/python3.10/subprocess.py", line 501, in run
#10 2.775     with Popen(*popenargs, **kwargs) as process:
#10 2.775   File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
#10 2.776     self._execute_child(args, executable, preexec_fn, close_fds,
#10 2.778   File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
#10 2.778     raise child_exception_type(errno_num, err_msg, err_filename)
#10 2.778 FileNotFoundError: [Errno 2] No such file or directory: '/.venv/bin/python'
------
executor failed running [/bin/sh -c pipenv install --deploy --clear --keep-outdated]: exit code: 1

```

The solution I found is:

```
COPY Pipfile* ./
RUN pip3 install pipenv==v2022.4.20
RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy --clear --keep-outdated
```

The build image is ubuntu:22.04, python-version 3.10.4

**Comment by andrewdotn** [comment]
I am having the same issue on the new Ubuntu 22.04 but not the previous 21.10.

I do not understand the problem but I have identified a workaround: `pip uninstall -y setuptools` seems to allow pipenv to run.

I can reproduce the issue without pipenv. Something about the act of installing the setuptools dependency specified in pipenv’s setup.py breaks virtualenv creation on Ubuntu 22.04; no `bin` dir gets created.

    FROM ubuntu:22.04

    RUN apt update \
        && DEBIAN_FRONTEND=noninteractive apt install -y python3-pip \
        && rm -rf /var/lib/apt/lists

    RUN adduser  user1

    USER user1
    WORKDIR /home/user1

    RUN pip install --user virtualenv 'setuptools>=60.0.0'
    RUN python3 -m virtualenv foo && foo/bin/python3 --version

fails with `/bin/sh: 1: foo/bin/python3: not found`

**Comment by kojibhy** [comment]
same problem:
pipenv: version 2022.4.21
Ubuntu 22.04 LTS
Python 3.10.4

```text
pipenv install requests
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.16.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Creating a virtualenv for this project...
Pipfile: /home/ubuntu/Downloads/Pipfile
Using /usr/bin/python3 (3.10.4) to create virtualenv...
⠧ Creating virtual environment...created virtual environment CPython3.10.4.final.0-64 in 185ms
  creator CPython3Posix(dest=/home/ubuntu/.local/share/virtualenvs/Downloads-UJGff8HK, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ubuntu/.local/share/virtualenv)
    added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/cli/options.py", line 56, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/cli/command.py", line 222, in install
    do_install(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/core.py", line 1964, in do_install
    ensure_project(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/core.py", line 552, in ensure_project
    ensure_virtualenv(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/core.py", line 485, in ensure_virtualenv
    do_create_virtualenv(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/core.py", line 1012, in do_create_virtualenv
    project._environment = Environment(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/environment.py", line 70, in __init__
    self._base_paths = self.get_paths()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/environment.py", line 394, in get_paths
    c = subprocess_run(command)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pipenv/utils/processes.py", line 75, in subprocess_run
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.local/share/virtualenvs/Downloads-UJGff8HK/bin/python'
```

what is see is virtualenv create complete other structure without bin
```
ls /home/ubuntu/.local/share/virtualenvs/Downloads-UJGff8HK/
lib  local  pyvenv.cfg
```

**Comment by nomis** [comment]
This happens with `setuptools>=60` on Ubuntu 22.04 with Python 3.10.4 but not on Ubuntu 20.04 with Python 3.8.10/3.9.5.

Downgrading setuptools to before version 60 works around the problem. Ubuntu 22.04 comes with version 59.6.0 but pipenv 2022.4.21 wants `setuptools>=60.0.0`.

**Comment by andrewdotn** [comment]
The (excellent!) bug report at https://github.com/pypa/setuptools/issues/3278 identifies the cause more precisely.

There are two better workarounds identified there:
  - Set the environment variable `SETUPTOOLS_USE_DISTUTILS=stdlib` when running pipenv.
  - Or change the default setting in a file with `sed -i.bak -e "s/var, 'local'/var, 'stdlib'/" ~/.local/lib/python3.10/site-packages/distutils-precedence.pth`

**Comment by limkin092** [comment]
@andrewdotn  this worked for me :)
@matteius yes, from one day to other it did not work...

**Comment by felipecrp** [comment]
@andrewdotn the `SETUPTOOLS_USE_DISTUTILS=stdlib` also worked for me.

**Comment by matteius** [comment]
@oz123 I am wondering what could have been different between `2022.4.20` and `2022.4.21` that might have caused this?

**Comment by matteius** [comment]
Ah I forgot that I updated the minimum version of pip and setuptools when I dropped 3.6 support -- I think I based it on the versions that had dropped 3.6 support of those projects:  https://github.com/pypa/pipenv/pull/5066/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R26

**Comment by epomatti** [comment]
@andrewdotn I had to export in order for it to work:

```sh
export SETUPTOOLS_USE_DISTUTILS=stdlib
```

**Comment by matteius** [comment]
I would like some guidance on what the proper resolution would be for pipenv -- should we loosen the versions of setuptools in the setup.py?  I am not convinced that we should allow such older versions of pip since we vendor in the latest pip, (I also thought we only used the pip internal to pipenv, and the fact that we use both I find troubling), anyway I am glad there is some work arounds, but I'd like to understand the path forward for this pipenv issue as well.

**Comment by nomis** [comment]
I don't think the version of pip affects this?

When the setuptools/virtualenv/distutils bug is resolved then pipenv can depend on the newer version of those.

The difference between `2022.4.20` and `2022.4.21` is that it requires `setuptools>=60` which has this problem. Ubuntu 22.04 was also released around the same time.

**Comment by emmmhx** [comment]
@andrewdotn trying to get rid of this warning:
`/home/danka/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release`
But the workaround you mentioned didn't solve it. Any ideas what's the issue here?

- python 3.10.4
- pip 22.0.4
- pipenv, version 2022.4.21

**Comment by matteius** [comment]
@emmmhx The deprecation warning shouldn't be causing an actual error ... is that `1.1build1` coming from your own package?

@nomis Ok sounds like a plan to open setuptools back up to the prior specifier.

**Comment by emmmhx** [comment]
@matteius This warning appears every time I run `pipenv` in terminal.

**Comment by felipecrp** [comment]
I also have these warnings every time I run pipenv. Although the command works, the warnings are undesired.

I'm using unto 22.04 with WSL2.

**Comment by matteius** [comment]
Can someone try this branch and see downgrading the setuptools specifier is enough?  https://github.com/pypa/pipenv/pull/5087

**Comment by felipecrp** [comment]
@matteius Sure. I tested and found the same problem.

I did the following commands:

```bash
$ pip uninstall pipenv
$ pip install "git+https://github.com/pypa/pipenv.git@issue-5075-setuptools"
```
The result was:
```bash
pipenv install
/home/user/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/user/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
Creating a virtualenv for this project...
Pipfile: /home/user/tmp/Pipfile
Using /usr/bin/python3 (3.10.4) to create virtualenv...
⠙ Creating virtual environment...created virtual environment CPython3.10.4.final.0-64 in 403ms
  creator CPython3Posix(dest=/home/user/.local/share/virtualenvs/tmp-K1LwcDUA, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/user/.local/share/virtualenv)
    added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Traceback (most recent call last):
  File "/home/user/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/cli/options.py", line 56, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/cli/command.py", line 222, in install
    do_install(
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/core.py", line 1965, in do_install
    ensure_project(
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/core.py", line 553, in ensure_project
    ensure_virtualenv(
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/core.py", line 486, in ensure_virtualenv
    do_create_virtualenv(
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/core.py", line 1013, in do_create_virtualenv
    project._environment = Environment(
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/environment.py", line 70, in __init__
    self._base_paths = self.get_paths()
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/environment.py", line 394, in get_paths
    c = subprocess_run(command)
  File "/home/user/.local/lib/python3.10/site-packages/pipenv/utils/processes.py", line 75, in subprocess_run
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.local/share/virtualenvs/tmp-K1LwcDUA/bin/python'
```

**Comment by felipecrp** [comment]
@andrewdotn @matteius If i uninstall setuptools, it works, but I still get the warnings.

```bash
$ pip uninstall pipenv
$pip uninstall setuptools
$ pip install "git+https://github.com/pypa/pipenv.git@issue-5075-setuptools"
$ pipenv install
```

The command successfully creates the env, but still with some warnings.

```
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
Creating a virtualenv for this project...
Pipfile: /home/user/tmp/Pipfile
Using /usr/bin/python3 (3.10.4) to create virtualenv...
⠸ Creating virtual environment...created virtual environment CPython3.10.4.final.0-64 in 202ms
  creator CPython3Posix(dest=/home/user/.local/share/virtualenvs/tmp-K1LwcDUA, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/user/.local/share/virtualenv)
    added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /home/user/.local/share/virtualenvs/tmp-K1LwcDUA
Creating a Pipfile for this project...
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Updated Pipfile.lock (e4eef2)!
Installing dependencies from Pipfile.lock (e4eef2)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

**Comment by nomis** [comment]
Those warnings are nothing to do with pipenv.

They're coming from pkg_resources and would need to be reported to Ubuntu, but this warning has been present for several Ubuntu LTS releases now.

**Comment by felipecrp** [comment]
I don't know but I only see them when I run `pipenv`.

**Comment by matteius** [comment]
@felipecrp its definitely been reported before the new versions about the warnings for pkg_resources.   Here is an example, and there are a couple more if you search the closed issues:  https://github.com/pypa/pipenv/issues/4960

**Comment by felipecrp** [comment]
I believe that the pull request solves this issue. Thank you all for the help!

**Comment by Michal-Kolomanski** [comment]
> @andrewdotn @matteius If I uninstall setuptools, it works, but I still get the warnings.
> 
> ```shell
> $ pip uninstall pipenv
> $ pip uninstall setuptools
> $ pip install "git+https://github.com/pypa/pipenv.git@issue-5075-setuptools"
> $ pipenv install
> ```
> 
> The command successfully creates the env, but still with some warnings.
> 
> ```
> /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
>   warnings.warn(
> /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
>   warnings.warn(
> Creating a virtualenv for this project...
> Pipfile: /home/user/tmp/Pipfile
> Using /usr/bin/python3 (3.10.4) to create virtualenv...
> ⠸ Creating virtual environment...created virtual environment CPython3.10.4.final.0-64 in 202ms
>   creator CPython3Posix(dest=/home/user/.local/share/virtualenvs/tmp-K1LwcDUA, clear=False, no_vcs_ignore=False, global=False)
>   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/user/.local/share/virtualenv)
>     added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.37.1
>   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
> 
> ✔ Successfully created virtual environment!
> Virtualenv location: /home/user/.local/share/virtualenvs/tmp-K1LwcDUA
> Creating a Pipfile for this project...
> Pipfile.lock not found, creating...
> Locking [dev-packages] dependencies...
> Locking [packages] dependencies...
> Updated Pipfile.lock (e4eef2)!
> Installing dependencies from Pipfile.lock (e4eef2)...
>   🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
> To activate this project's virtualenv, run pipenv shell.
> Alternatively, run a command inside the virtualenv with pipenv run.
> ```
OS: `Ubuntu 20.04`
I came here because I was getting a very similar error message when I was trying to create pipenv virtualenv with Python 3.10 (other versions of python were working perfectly fine). 
When I was applying:
`pipenv install --python 3.10`
Virtualenv in `/virtualenvs` was created but without `bin` folder at all which caused an error.

After applying those commands:
> ```shell
> $ pip uninstall pipenv
> $ pip uninstall setuptools
> $ pip install "git+https://github.com/pypa/pipenv.git@issue-5075-setuptools"
> $ pipenv install
> ```
None of the Python versions works for me now... I found it impossible to create any pipenv environment. 
Now after `pipenv install` there is no virtualenv created in  `/virtualenvs` at all.
Stack trace:
```
recommender-systemmichal@michal-ThinkPad-T590:~/Desktop/Cyfronet/Recommender/recommender-system$ pipenv install
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Traceback (most recent call last):
  File "/home/michal/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/cli/options.py", line 56, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/cli/command.py", line 222, in install
    do_install(
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/core.py", line 1965, in do_install
    ensure_project(
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/core.py", line 553, in ensure_project
    ensure_virtualenv(
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/core.py", line 473, in ensure_virtualenv
    python = ensure_python(project, three=three, python=python)
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/core.py", line 362, in ensure_python
    path_to_python = find_a_system_python(python)
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/core.py", line 329, in find_a_system_python
    return next(iter(finder.find_all_python_versions()), None)
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 312, in find_all_python_versions
    python_version_dict = getattr(self.system_path, "python_version_dict", {})
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 120, in system_path
    self._system_path = self.create_system_path()
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 82, in create_system_path
    return pyfinder_path.SystemPath.create(
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 694, in create
    instance = instance._run_setup()
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 262, in _run_setup
    paths[p] = new_instance.get_path(p.joinpath(bin_dir))
  File "/home/michal/.local/lib/python3.8/site-packages/pipenv/vendor/pythonfinder/models/path.py", line 450, in get_path
    raise ValueError("Path not found or generated: {0!r}".format(path))
ValueError: Path not found or generated: PosixPath('/home/michal/.local/share/virtualenvs/recommender-system-dfVHVYpy/bin')
```
For me, this fix isn't fixing the issue.

**Comment by simurgh9** [comment]
For those mortals here who are still confused and questioning--"what commands do I run to fix this..." which was definitely not moi, try,

```
pip install --upgrade --user setuptools==58.3.0
```

**Comment by khteh** [comment]
Bump ino this error on Ubuntu 22.04 Python 3.10.4 even after `export SETUPTOOLS_USE_DISTUTILS=stdlib` and upgraded setuptools.
```
$ pip install --upgrade --user setuptools
Requirement already satisfied: setuptools in /home/khteh/.local/lib/python3.10/site-packages (61.0.0)
Collecting setuptools
  Downloading setuptools-62.2.0-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 17.8 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 61.0.0
    Uninstalling setuptools-61.0.0:
      Successfully uninstalled setuptools-61.0.0
Successfully installed setuptools-62.2.0
```
```
$ pipenv install
/home/khteh/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/khteh/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Installing dependencies from Pipfile.lock (cb1e45)...
Traceback (most recent call last):
  File "/home/khteh/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/cli/options.py", line 56, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/cli/command.py", line 222, in install
    do_install(
  File "/usr/local/lib/python3.10/dist-packages/pipenv/core.py", line 2091, in do_install
    do_init(
  File "/usr/local/lib/python3.10/dist-packages/pipenv/core.py", line 1335, in do_init
    do_install_dependencies(
  File "/usr/local/lib/python3.10/dist-packages/pipenv/core.py", line 870, in do_install_dependencies
    batch_install(
  File "/usr/local/lib/python3.10/dist-packages/pipenv/core.py", line 728, in batch_install
    deps_to_install = [
  File "/usr/local/lib/python3.10/dist-packages/pipenv/core.py", line 729, in <listcomp>
    dep for dep in deps_to_install if not project.environment.is_satisfied(dep)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/project.py", line 319, in environment
    self._environment = self.get_environment(allow_global=allow_global)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/project.py", line 299, in get_environment
    environment = Environment(
  File "/usr/local/lib/python3.10/dist-packages/pipenv/environment.py", line 70, in __init__
    self._base_paths = self.get_paths()
  File "/usr/local/lib/python3.10/dist-packages/pipenv/environment.py", line 394, in get_paths
    c = subprocess_run(command)
  File "/usr/local/lib/python3.10/dist-packages/pipenv/utils/processes.py", line 75, in subprocess_run
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/khteh/.local/share/virtualenvs/PythonRestAPI-JI5RzKtM/bin/python'
```

**Comment by andrewdotn** [comment]
@khteh I can’t reproduce that, are you able to provide a script that does so in a fresh container or VM? The following Dockerfile works for me and uses the latest ubuntu, Python, pipenv==2022.5.2, and setuptools==62.2.0:

```
FROM ubuntu:22.04

RUN apt update \
    && DEBIAN_FRONTEND=noninteractive apt install -y python3-pip git \
    && rm -rf /var/lib/apt/lists

RUN adduser  user1

USER user1
WORKDIR /home/user1

RUN pip install --user pipenv
RUN pip install -U --user setuptools==62.2.0
RUN touch Pipfile && SETUPTOOLS_USE_DISTUTILS=stdlib python3 -m pipenv install
RUN python3 -m pipenv run which python && python3 -m pipenv run python --version
```

**Comment by khteh** [comment]
Bare metal. Not docker.

**Comment by alterclaw** [comment]
Hi there. Thank you very much for the suggested solution. I'm a big fan of pipenv for professional management of virtual environments, and I had to switch to _poetry_ for a while, which was a pretty awful experience :-)

### Ok, what now
I've tried @andrewdotn 's recipe:
```bash
sed -i.bak -e "s/var, 'local'/var, 'stdlib'/" ~/.local/lib/python3.10/site-packages/distutils-precedence.pth
```
after this pipenv works fine, but I get warning message before any command is done:
```
~ $ pipenv --version
/home/master/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
pipenv, version 2022.5.2

```
My package versions:
```
setuptools             62.3.2
pip                    22.1
pipenv                 2022.5.2
```

**OS**: Pop!_OS 22.04 (based on Ubuntu 22.04)
**Python**: 3.10.4

I didn't quite understand from the correspondence whether the issue was solved. If issue is solved, please let me know how it can be fixed locally.

Thanks!

**Comment by matteius** [comment]
@alterclaw  what happens if you pin your version of pip to 22.0.4?

**Comment by khteh** [comment]
> @khteh I can’t reproduce that, are you able to provide a script that does so in a fresh container or VM? The following Dockerfile works for me and uses the latest ubuntu, Python, pipenv==2022.5.2, and setuptools==62.2.0:
> 
> ```
> FROM ubuntu:22.04
> 
> RUN apt update \
>     && DEBIAN_FRONTEND=noninteractive apt install -y python3-pip git \
>     && rm -rf /var/lib/apt/lists
> 
> RUN adduser  user1
> 
> USER user1
> WORKDIR /home/user1
> 
> RUN pip install --user pipenv
> RUN pip install -U --user setuptools==62.2.0
> RUN touch Pipfile && SETUPTOOLS_USE_DISTUTILS=stdlib python3 -m pipenv install
> RUN python3 -m pipenv run which python && python3 -m pipenv run python --version
> ```

I run into this problem on bare metal. Not docker container.

**Comment by electron-farmer** [comment]
Mentioning this issue again in case you haven't seen the write up. https://github.com/pypa/setuptools/issues/3278

I was able to get unblocked by following the steps mentioned in @andrewdotn's post, https://github.com/pypa/pipenv/issues/5075#issuecomment-1107460002, and blowing away my existing pipenv in `~/.local/share/virtualenvs/MY_PROJECT` then recreating the env.

**Comment by MahdiJafari1** [comment]
> > @andrewdotn I had to export in order for it to work:
> > ```shell
> > export SETUPTOOLS_USE_DISTUTILS=stdlib
> > ```
> 
> This worked for me as well.
> 
> System Information:
> 
> Python
> 
> ```
> Python 3.10.4
> pipenv, version 2022.4.20
> ```
> 
> Kernel
> 
> ```
> Linux cj-Z 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> Ubuntu:
> 
> ```
> Distributor ID: Ubuntu
> Description:    Ubuntu 22.04 LTS
> Release:        22.04
> Codename:       jammy
> ```

Thank you. exporting solved my issue

**Comment by flichtenheld** [comment]
I have this problem with Fedora 36 now and the previous `SETUPTOOLS_USE_DISTUTILS=stdlib` workaround does not fix it. The following Docker file reproduces the problem:

```
FROM fedora:36

RUN yum install -y python3-devel which

RUN useradd user1

USER user1
WORKDIR /home/user1

RUN pip install --user pipenv
RUN pip install -U --user setuptools==62.2.0
RUN touch Pipfile && SETUPTOOLS_USE_DISTUTILS=stdlib python3 -m pipenv install
RUN python3 -m pipenv run which python && python3 -m pipenv run python --version
```

```
 > [7/8] RUN touch Pipfile && SETUPTOOLS_USE_DISTUTILS=stdlib python3 -m pipenv install:
#10 1.261 Warning: the environment variable LANG is not set!
#10 1.261 We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
#10 1.420 Creating a virtualenv for this project...
#10 1.420 Pipfile: /home/user1/Pipfile
#10 1.432 Using /usr/bin/python3 (3.10.4) to create virtualenv...
⠧ Creating virtual environment...created virtual environment CPython3.10.4.final.0-64 in 417ms
#10 2.000   creator CPython3Posix(dest=/home/user1/.local/share/virtualenvs/user1-SzSdR0AK, clear=False, no_vcs_ignore=False, global=False)
#10 2.000   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/user1/.local/share/virtualenv)
#10 2.000     added seed packages: pip==22.0.4, setuptools==62.1.0, wheel==0.37.1
#10 2.000   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
#10 2.000
#10 2.079✔ Successfully created virtual environment!
#10 2.081 Traceback (most recent call last):
#10 2.081   File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
#10 2.081     return _run_code(code, main_globals, None,
#10 2.081   File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
#10 2.082     exec(code, run_globals)
#10 2.082   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/__main__.py", line 4, in <module>
#10 2.082     cli()
#10 2.082   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
#10 2.082     return self.main(*args, **kwargs)
#10 2.082   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/cli/options.py", line 56, in main
#10 2.083     return super().main(*args, **kwargs, windows_expand_args=False)
#10 2.083   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1053, in main
#10 2.083     rv = self.invoke(ctx)
#10 2.083   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
#10 2.084     return _process_result(sub_ctx.command.invoke(sub_ctx))
#10 2.084   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
#10 2.084     return ctx.invoke(self.callback, **ctx.params)
#10 2.084   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
#10 2.085     return __callback(*args, **kwargs)
#10 2.085   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
#10 2.085     return ctx.invoke(f, obj, *args, **kwargs)
#10 2.085   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
#10 2.085     return __callback(*args, **kwargs)
#10 2.086   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/cli/command.py", line 222, in install
#10 2.086     do_install(
#10 2.086   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/core.py", line 1965, in do_install
#10 2.086     ensure_project(
#10 2.086   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/core.py", line 553, in ensure_project
#10 2.087     ensure_virtualenv(
#10 2.087   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/core.py", line 486, in ensure_virtualenv
#10 2.087     do_create_virtualenv(
#10 2.087   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/core.py", line 1013, in do_create_virtualenv
#10 2.087     project._environment = Environment(
#10 2.087   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/environment.py", line 70, in __init__
#10 2.087     self._base_paths = self.get_paths()
#10 2.088   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/environment.py", line 394, in get_paths
#10 2.088     c = subprocess_run(command)
#10 2.088   File "/home/user1/.local/lib/python3.10/site-packages/pipenv/utils/processes.py", line 75, in subprocess_run
#10 2.088     return subprocess.run(
#10 2.088   File "/usr/lib64/python3.10/subprocess.py", line 501, in run
#10 2.089     with Popen(*popenargs, **kwargs) as process:
#10 2.089   File "/usr/lib64/python3.10/subprocess.py", line 966, in __init__
#10 2.089     self._execute_child(args, executable, preexec_fn, close_fds,
#10 2.089   File "/usr/lib64/python3.10/subprocess.py", line 1842, in _execute_child
#10 2.089     raise child_exception_type(errno_num, err_msg, err_filename)
#10 2.090 FileNotFoundError: [Errno 2] No such file or directory: '/home/user1/.local/share/virtualenvs/user1-SzSdR0AK/local/bin/python'
------
executor failed running [/bin/sh -c touch Pipfile && SETUPTOOLS_USE_DISTUTILS=stdlib python3 -m pipenv install]: exit code: 1
```

While it works perfectly well with Fedora 35.

**Comment by llbbl** [comment]
This is happening on Dreamhost

```
└─[$] pip --version                                                                                  
pip 21.3.1 from /home/<user_name>/.local/lib/python3.6/site-packages/pip (python 3.6)
└─[$] python --version                                                                                       
Python 3.6.9
└─[$] which python                                                                                            
python: aliased to /usr/bin/python3
```

fixed it by downgrading with
```
pip install --upgrade --user setuptools==58.3.0
```

the error
```
└─[$] pipenv                                                                                                       
/home/<username>/.local/lib/python3.6/site-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: 2.17.12ubuntu1.1 is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
/home/<username>/.local/lib/python3.6/site-packages/pkg_resources/__init__.py:119: PkgResourcesDeprecationWarning: 0.18ubuntu0.18.04.1 is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,
```

**Comment by khteh** [comment]
Remove `~/.local/share/virtualenvs/*` works for me.

**Comment by matteius** [comment]
Was this resolved by the `2022.6.7` release?

**Comment by khteh** [comment]
Can close

**Comment by featdd** [comment]
@matteius the warning output still persists for me

I run a `ubuntu:jammy` docker image & use the `ppa:deadsnakes/ppa` apt repository.
I also checked the current pipenv version in the image and it is 2022.6.7

I still receive this warnings as output on every pipenv python call:

```
packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release

  warnings.warn(

/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release

  warnings.warn(
```

**Comment by matteius** [comment]
@featdd  That isn't an error, and definitely not related to pipenv.  It is a warning between pkg_resoruces and your ubuntu distribution.   Nothing we can do about that in `pipenv` -- it has been requested and discussed many times though.

**Comment by featdd** [comment]
@matteius It happens with latest ubuntu jammy docker, I don't really get what else could be the issue.

[Other sources](https://askubuntu.com/questions/1406952/what-is-the-meaning-of-this-pkgresourcesdeprecationwarning-warning-from-pipenv) always state that pipenv causes the issue.

There isn't anything else installed, the only workaround I have for now is to downgrade setuptools to 58.3.0

**Comment by matteius** [comment]
@featdd Could it have anything to do with the Deadsnakes repository and their version of Python?   That source you linked to doesn't really determine how it is pipenv that is causing it.  Without a stack trace that shows where pipenv code is invoking it, its hard to tell.  I reviewed usages of pkg_resources in pipenv and came to the conclusion of why would pipenv need to know the operating system version?  I could find anywhere in the code that it does.  So whatever is invoking pkg_resources to check on `0.1.43ubuntu1` is a mystery to me.

**Comment by OrinaOisera** [comment]
What can one do when running on Ubuntu 20.04.4 LTS and facing the same error.?
I have tried all the solutions mentinedabove.

**Comment by jixbo** [comment]
I'm still facing this issue in Ubuntu 22.04 too. Removing ~/.local/share/virtualenvs/ followed by `export SETUPTOOLS_USE_DISTUTILS=stdlib` works for me as a temporary workaround. Warnings are still there.

```
jixbo@thinkpad:~$ pip --version
pip 22.1.2 from /home/jixbo/.local/lib/python3.10/site-packages/pip (python 3.10)
jixbo@thinkpad:~$ python --version
Python 3.10.4
jixbo@thinkpad:~$ which python
/usr/bin/python
```

**Comment by matteius** [comment]
Can you try the `main` branch of `pipenv` to see if its any better?  We are planning on a doing a release of the latest `main` later this week?

**Comment by flichtenheld** [comment]
> I have this problem with Fedora 36 now and the previous `SETUPTOOLS_USE_DISTUTILS=stdlib` workaround does not fix it. The following Docker file reproduces the problem:
> 
> ```
> FROM fedora:36
> 
> RUN yum install -y python3-devel which
> 
> RUN useradd user1
> 
> USER user1
> WORKDIR /home/user1
> 
> RUN pip install --user pipenv
> RUN pip install -U --user setuptools==62.2.0
> RUN touch Pipfile && SETUPTOOLS_USE_DISTUTILS=stdlib python3 -m pipenv install
> RUN python3 -m pipenv run which python && python3 -m pipenv run python --version
> ```

Retested this. Original report was with 2022.5.2. Not reproducible with 2022.6.7 nor main. So all good from my side, it seems (FYI: @matteius)

**Comment by khteh** [comment]
It happens again even after I remove `.local/share/virtualenvs/jupyter-notebooks-46_jCq9y`:
```
$ pipenv --version
/home/khteh/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/khteh/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
pipenv, version 2022.7.24
khteh@khteh-p17-2i:/usr/src/jupyter-notebooks 2020 $ pipenv shell
/home/khteh/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/khteh/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Creating a virtualenv for this project...
Pipfile: /usr/src/jupyter-notebooks/Pipfile
Using /usr/bin/python (3.10.4) to create virtualenv...
⠙ Creating virtual environment...created virtual environment CPython3.10.4.final.0-64 in 83ms
  creator CPython3Posix(dest=/home/khteh/.local/share/virtualenvs/jupyter-notebooks-46_jCq9y, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/khteh/.local/share/virtualenv)
    added seed packages: pip==22.1.2, setuptools==62.3.3, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Traceback (most recent call last):
  File "/home/khteh/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/cli/options.py", line 56, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/cli/command.py", line 435, in shell
    do_shell(
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/core.py", line 2444, in do_shell
    ensure_project(
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/core.py", line 553, in ensure_project
    ensure_virtualenv(
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/core.py", line 486, in ensure_virtualenv
    do_create_virtualenv(
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/core.py", line 1019, in do_create_virtualenv
    project._environment = Environment(
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/environment.py", line 72, in __init__
    self._base_paths = self.get_paths()
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/environment.py", line 394, in get_paths
    c = subprocess_run(command)
  File "/home/khteh/.local/lib/python3.10/site-packages/pipenv/utils/processes.py", line 75, in subprocess_run
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/khteh/.local/share/virtualenvs/jupyter-notebooks-46_jCq9y/bin/python'
khteh@khteh-p17-2i:/usr/src/jupyter-notebooks 2021 $ echo $SETUPTOOLS_USE_DISTUTILS
stdlib
```

**Comment by khteh** [comment]
Why is `pipenv` behaving so strange?
```
$ which pipenv
/usr/local/bin/pipenv
$ pipenv --version
bash: /home/khteh/.local/bin/pipenv: No such file or directory
```

**Comment by khteh** [comment]
`pipenv install --python=/path/to/python` resoves it.

**Comment by dcriado** [comment]
I was getting the same `FileNotFoundError` alongwith two `PkgResourcesDeprecationWarning`.

<details>
<summary>See warnings</summary>

```
~/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
~/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
```
</details>

Searching for the origin of those warnings, I stumbled upon this [StackOverflow question](https://askubuntu.com/questions/1406952/what-is-the-meaning-of-this-pkgresourcesdeprecationwarning-warning-from-pipenv). Following the accepted answer, I downgraded `setuptools` from version 65.3.0 to version 58.3.0:

```
pip install --upgrade --user setuptools==58.3.0
```

After that, I rerun `pipenv install` and **everything worked properly**: a bin/python path was found within the virtualenvs directory, and no warnings were issued.

- Ubuntu 22.04.1 LTS
- Python 3.10.4
- Pip 22.2.2
- Pipenv 2022.8.24

**Comment by tonydattolo** [comment]
still running into this issue

It looks like it is trying to graph the wrong executable location for the python interpreter. it is looking for `/.venv/bin/python` but it should be looking for  `/.venv/local/bin/python`

```bash
Traceback (most recent call last):
  File "/home/tony/.local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/cli/options.py", line 57, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/cli/command.py", line 398, in shell
    do_shell(
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/core.py", line 2533, in do_shell
    ensure_project(
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/core.py", line 526, in ensure_project
    ensure_virtualenv(
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/core.py", line 459, in ensure_virtualenv
    do_create_virtualenv(
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/core.py", line 964, in do_create_virtualenv
    project._environment = Environment(
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/environment.py", line 80, in __init__
    self._base_paths = self.get_paths()
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/environment.py", line 391, in get_paths
    c = subprocess_run(command)
  File "/home/tony/.local/lib/python3.10/site-packages/pipenv/utils/processes.py", line 75, in subprocess_run
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/tony/repos/graphql-playground/backend/.venv/bin/python'
```

- Ubuntu 22.04.1 LTS
- Python 3.10.4
- pipenv 2022.9.8
- pip 22.2.2

**Comment by matteius** [comment]
The `PkgResourcesDeprecationWarning` were finally solved -- perhaps also the `FileNotFoundError` -- could someone re-check?

**Comment by Reddine** [comment]
> perhaps also the `FileNotFoundError` -- could someone re-check?

I still have to use https://github.com/pypa/pipenv/issues/5075#issuecomment-1107460002 solution.

- Ubuntu 22.04.1 LTS
- pipenv, version 2022.9.21
- Python 3.10.6
- pip 22.2.2

**Comment by matteius** [comment]
I am now getting the same error now that I upgraded my Ubuntu VM (22.0.4) ... the `export SETUPTOOLS_USE_DISTUTILS=stdlib` workaround did not seem to help in my case.

**Comment by Reddine** [comment]
> I am now getting the same error now that I upgraded my Ubuntu VM (22.0.4) ... the `export SETUPTOOLS_USE_DISTUTILS=stdlib` workaround did not seem to help in my case.

After installing Ubuntu I used this command to update pipenv
`pip install --upgrade pipenv`
and I have this shell configuration:
```
alias python=python3
export PATH="/home/MYUSERNAME/.local/bin:$PATH"
```
Not sure if that helps!

**Comment by matteius** [comment]
The problem for making this better in pipenv is how to tell when it should be `{base}/bin` vs `{base}/local/bin` ... the way its coded right now is it referencing a specific scheme in sysconfig that ends up being wrong for ubuntu.  I am not sure if this patch will have side-effects, but I started a branch to begin addressing this issue.  https://github.com/pypa/pipenv/pull/5376

**Comment by matteius** [comment]
I spent some more time on this, and I think the best workaround, which is reflected in https://github.com/pypa/pipenv/pull/5376/files, is to use `--creator=venv` when pipenv creates new virtualenvs, this seems to solve all of the problems I found using pipenv out of the box on the latest ubuntu, but I think it may means once we release this, folks that are using the workaround would need to clear out those virtualenvs and let them be created fresh.

**Comment by oz123** [comment]
Does this work if python3-venv package is missing?

**Comment by matteius** [comment]
@oz123 
```
matteius@matteius-VirtualBox:~/pipenv$ pip uninstall python3-venv
WARNING: Skipping python3-venv as it is not installed.
matteius@matteius-VirtualBox:~/pipenv$ pip uninstall python-venv
WARNING: Skipping python-venv as it is not installed.
```

**Comment by oz123** [comment]
You need to check with `apt`:
````
$ sudo apt remove python3-venv
```

**Comment by matteius** [comment]
@oz123 Appears to work:
```
matteius@matteius-VirtualBox:~/pipenv$ sudo apt remove python3-venv
[sudo] password for matteius: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following package was automatically installed and is no longer required:
  systemd-hwe-hwdb
Use 'sudo apt autoremove' to remove it.
The following packages will be REMOVED:
  python3-venv
0 upgraded, 0 newly installed, 1 to remove and 17 not upgraded.
After this operation, 6,144 B disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 297188 files and directories currently installed.)
Removing python3-venv (3.10.6-1~22.04) ...
matteius@matteius-VirtualBox:~/pipenv$ pipenv --rm
Removing virtualenv (/home/matteius/.virtualenvs/pipenv-wR0g04D-)...
matteius@matteius-VirtualBox:~/pipenv$ pipenv sync -d
Creating a virtualenv for this project...
Pipfile: /home/matteius/pipenv/Pipfile
Using /usr/bin/python3 (3.10.6) to create virtualenv...
⠸ Creating virtual environment...created virtual environment CPython3.10.6.final.0-64 in 222ms
  creator Venv(dest=/home/matteius/.virtualenvs/pipenv-wR0g04D-, clear=False, no_vcs_ignore=False, global=False, describe=CPython3Posix)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/matteius/.local/share/virtualenv)
    added seed packages: pip==22.2.2, setuptools==65.3.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/matteius/.virtualenvs/pipenv-wR0g04D-
Installing dependencies from Pipfile.lock (ccf32d)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!
matteius@matteius-VirtualBox:~/pipenv$ pipenv shell
Launching subshell in virtual environment...
 . /home/matteius/.virtualenvs/pipenv-wR0g04D-/bin/activate
matteius@matteius-VirtualBox:~/pipenv$  . /home/matteius/.virtualenvs/pipenv-wR0g04D-/bin/activate
(pipenv-wR0g04D-) matteius@matteius-VirtualBox:~/pipenv$ 
```

**Comment by oz123** [comment]
It appears that Ubuntu is distributing `venv` as part of the standard libpython ! It used to be a separate package in older times.

**Comment by kiprotichdominic** [comment]
THIS WORKED FOR ME
> I'm still facing this issue in Ubuntu 22.04 too. Removing ~/.local/share/virtualenvs/ followed by `export SETUPTOOLS_USE_DISTUTILS=stdlib` works for me as a temporary workaround. Warnings are still there.
> 
> ```
> jixbo@thinkpad:~$ pip --version
> pip 22.1.2 from /home/jixbo/.local/lib/python3.10/site-packages/pip (python 3.10)
> jixbo@thinkpad:~$ python --version
> Python 3.10.4
> jixbo@thinkpad:~$ which python
> /usr/bin/python
> ```

**Comment by matteius** [comment]
Fix will be in the next release.

**Comment by yogenderPalChandra** [comment]
none of the above worked for me, what worked was simply removing the already created venv:
`pipenv --rm`
