### ISSUE TITLE
python_full_version vs python_version

### ISSUE THREAD

**Issue by glensc** [pypa/pipenv#5499]
### Issue description

Do you know why pipenv generates extra diffs changing `python_version` to `python_full_version` and vice versa? And seemingly unrelated package updates.

At first I thought it was due to mixing `pipenv` versions, and created bug report to dependabot:
- https://github.com/dependabot/dependabot-core/issues/6091

but now created 3 commits sequentially with same version and the `python_version` was changed to `python_full_version` in one commit and `python_full_version` to `python_version` in another commit.

Branch:
- https://github.com/glensc/PlexTraktSync/tree/da587c0fbd2b40a1503445c916fbdd1faa55cda2
   - first uninstall package (`pipenv uninstall requests-cache`): https://github.com/glensc/PlexTraktSync/commit/287fc25b1daa5fce28d078f9a09eb7cb1be8c83c
   - then install without version specifier (`pipenv install requests-cache`): https://github.com/glensc/PlexTraktSync/commit/f766896ca00284b7155d125acf5895188f755741
   - then install again with version specifier (`pipenv install requests-cache==0.9.7`): https://github.com/glensc/PlexTraktSync/commit/da587c0fbd2b40a1503445c916fbdd1faa55cda2

So, I noticed:
- The uninstall changed `python_version` to `python_full_version` for `charset-normalizer`
- in first install command `python_version`  was changed to `python_full_version`  for `pfzy`, `pygments` packages
- in second install command python_full_version was changed to python_version for `pfzy` package

The test is ran with version that dependabot suppsedly runs (`pipenv==2022.4.8`):
- https://github.com/dependabot/dependabot-core/blob/0ac4e37da9bb6c054ab75116a4e891404490a342/python/helpers/requirements.txt

but it has happened with newer versions too.

### Expected result

Consistent, Pipfile.lock, is it `python_full_version` or `python_version` doesn't matter as long it sticks to one variant.

sometimes it changes python_version < '4' to python_version < '4.0', drops python_version >= '3.6':
- https://github.com/Taxel/PlexTraktSync/commit/31516d211b291331a6b4786bddc95e5e1242f6ba

### Actual result

When possible, provide the verbose output (`--verbose`), especially for locking and dependencies resolving issues.

### Steps to replicate

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.4.8'`

Python installations found:

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.10.8',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '19.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT '
                     '2022; root:xnu-6153.141.66~1/RELEASE_X86_64',
 'python_full_version': '3.10.8',
 'python_version': '3.10',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `SHELL`

Pipenv–specific environment variables:

 - `PIPENV_VERBOSITY`: `-1`

Debug–specific environment variables:

  - `SHELL`: `/usr/local/bin/bash`
  - `EDITOR`: `/usr/local/bin/nvim`
  - `LANG`: `en_US.UTF-8`

---------------------------

Contents of `Pipfile` ('/Users/glen/MegaSync/scm/plex/PlexTraktSync/Pipfile'):

```toml
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]

[packages]
appdirs = "==1.4.4"
certifi = "==2022.9.24"
click = "==8.1.3"
deprecated = "==1.2.13"
inquirerpy = "==0.3.4"
oauthlib = "==3.2.2"
plexapi = "==4.13.1"
python-dotenv = "==0.21.0"
python-git-info = "==0.8.2"
pytrakt = "==3.4.13"
pyyaml = "==6.0"
requests = ">=2.25.1"
rich = "==12.6.0"
tqdm = "==4.64.1"
urllib3 = ">=1.26.6"
websocket-client = "==1.4.2"
requests-cache = "==0.9.7"

[requires]
python_version = "3"

[scripts]
plextraktsync = "python -m plextraktsync"

```

Contents of `Pipfile.lock` ('/Users/glen/MegaSync/scm/plex/PlexTraktSync/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "81b6c97ff92c44a5419dbf6c7d3e5c5377ece1359c4d6e57dee0b3629c24a694"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "appdirs": {
            "hashes": [
                "sha256:7d5d0167b2b1ba821647616af46a749d1c653740dd0d2415100fe26e27afdf41",
                "sha256:a841dacd6b99318a741b166adb07e19ee71a274450e68237b4650ca1055ab128"
            ],
            "index": "pypi",
            "version": "==1.4.4"
        },
        "attrs": {
            "hashes": [
                "sha256:29adc2665447e5191d0e7c568fde78b21f9672d344281d0c6e1ab085429b22b6",
                "sha256:86efa402f67bf2df34f51a335487cf46b1ec130d02b8d39fd248abfd30da551c"
            ],
            "markers": "python_version >= '3.5'",
            "version": "==22.1.0"
        },
        "cattrs": {
            "hashes": [
                "sha256:bc12b1f0d000b9f9bee83335887d532a1d3e99a833d1bf0882151c97d3e68c21",
                "sha256:f0eed5642399423cf656e7b66ce92cdc5b963ecafd041d1b24d136fdde7acf6d"
            ],
            "markers": "python_version >= '3.7'",
            "version": "==22.2.0"
        },
        "certifi": {
            "hashes": [
                "sha256:0d9c601124e5a6ba9712dbc60d9c53c21e34f5f641fe83002317394311bdce14",
                "sha256:90c1a32f1d68f940488354e36370f6cca89f0f106db09518524c88d6ed83f382"
            ],
            "index": "pypi",
            "version": "==2022.9.24"
        },
        "charset-normalizer": {
            "hashes": [
                "sha256:5a3d016c7c547f69d6f81fb0db9449ce888b418b5b9952cc5e6e66843e9dd845",
                "sha256:83e9a75d1911279afd89352c68b45348559d1fc0506b054b346651b5e7fee29f"
            ],
            "markers": "python_full_version >= '3.6.0'",
            "version": "==2.1.1"
        },
        "click": {
            "hashes": [
                "sha256:7682dc8afb30297001674575ea00d1814d808d6a36af415a82bd481d37ba7b8e",
                "sha256:bb4d8133cb15a609f44e8213d9b391b0809795062913b383c62be0ee95b1db48"
            ],
            "index": "pypi",
            "version": "==8.1.3"
        },
        "commonmark": {
            "hashes": [
                "sha256:452f9dc859be7f06631ddcb328b6919c67984aca654e5fefb3914d54691aed60",
                "sha256:da2f38c92590f83de410ba1a3cbceafbc74fee9def35f9251ba9a971d6d66fd9"
            ],
            "version": "==0.9.1"
        },
        "deprecated": {
            "hashes": [
                "sha256:43ac5335da90c31c24ba028af536a91d41d53f9e6901ddb021bcc572ce44e38d",
                "sha256:64756e3e14c8c5eea9795d93c524551432a0be75629f8f29e67ab8caf076c76d"
            ],
            "index": "pypi",
            "version": "==1.2.13"
        },
        "exceptiongroup": {
            "hashes": [
                "sha256:542adf9dea4055530d6e1279602fa5cb11dab2395fa650b8674eaec35fc4a828",
                "sha256:bd14967b79cd9bdb54d97323216f8fdf533e278df937aa2a90089e7d6e06e5ec"
            ],
            "markers": "python_version < '3.11'",
            "version": "==1.0.4"
        },
        "idna": {
            "hashes": [
                "sha256:814f528e8dead7d329833b91c5faa87d60bf71824cd12a7530b5526063d02cb4",
                "sha256:90b77e79eaa3eba6de819a0c442c0b4ceefc341a7a2ab77d7562bf49f425c5c2"
            ],
            "markers": "python_version >= '3.5'",
            "version": "==3.4"
        },
        "inquirerpy": {
            "hashes": [
                "sha256:89d2ada0111f337483cb41ae31073108b2ec1e618a49d7110b0d7ade89fc197e",
                "sha256:c65fdfbac1fa00e3ee4fb10679f4d3ed7a012abf4833910e63c295827fe2a7d4"
            ],
            "index": "pypi",
            "version": "==0.3.4"
        },
        "oauthlib": {
            "hashes": [
                "sha256:8139f29aac13e25d502680e9e19963e83f16838d48a0d71c287fe40e7067fbca",
                "sha256:9859c40929662bec5d64f34d01c99e093149682a3f38915dc0655d5a633dd918"
            ],
            "index": "pypi",
            "version": "==3.2.2"
        },
        "pfzy": {
            "hashes": [
                "sha256:5f50d5b2b3207fa72e7ec0ef08372ef652685470974a107d0d4999fc5a903a96",
                "sha256:717ea765dd10b63618e7298b2d98efd819e0b30cd5905c9707223dceeb94b3f1"
            ],
            "markers": "python_version >= '3.7' and python_version < '4'",
            "version": "==0.3.4"
        },
        "plexapi": {
            "hashes": [
                "sha256:d3b811624cd3fba45e5d993c44f81168be44d8d3a795f9a6ca0dc47f35267c77",
                "sha256:e047dcb07d2dccb863ff9bace1999e1113119097be1517460f2b1f50cfcf7c74"
            ],
            "index": "pypi",
            "version": "==4.13.1"
        },
        "prompt-toolkit": {
            "hashes": [
                "sha256:535c29c31216c77302877d5120aef6c94ff573748a5b5ca5b1b1f76f5e700c73",
                "sha256:ced598b222f6f4029c0800cefaa6a17373fb580cd093223003475ce32805c35b"
            ],
            "markers": "python_full_version >= '3.6.2'",
            "version": "==3.0.33"
        },
        "pygments": {
            "hashes": [
                "sha256:56a8508ae95f98e2b9bdf93a6be5ae3f7d8af858b43e02c5a2ff083726be40c1",
                "sha256:f643f331ab57ba3c9d89212ee4a2dabc6e94f117cf4eefde99a0574720d14c42"
            ],
            "markers": "python_full_version >= '3.6.0'",
            "version": "==2.13.0"
        },
        "python-dotenv": {
            "hashes": [
                "sha256:1684eb44636dd462b66c3ee016599815514527ad99965de77f43e0944634a7e5",
                "sha256:b77d08274639e3d34145dfa6c7008e66df0f04b7be7a75fd0d5292c191d79045"
            ],
            "index": "pypi",
            "version": "==0.21.0"
        },
        "python-git-info": {
            "hashes": [
                "sha256:6417d2385d4dcbd411b4456b4edfcb97e911e0564e52f68524cef0977845ba35",
                "sha256:8ea2efa3b62db47443e7264410fde8b0383a05a6025b48fcc5c3df7b51ecae5b"
            ],
            "index": "pypi",
            "version": "==0.8.2"
        },
        "pytrakt": {
            "hashes": [
                "sha256:201bb2009812f8cd83bfa20341f723c92105ba9b71e5f87e5b90ba083cb3ad25",
                "sha256:7b647d7f4d71ce747b2119576ecb9d11b353103f938bc4f6bb7b02c880512642"
            ],
            "index": "pypi",
            "version": "==3.4.13"
        },
        "pyyaml": {
            "hashes": [
                "sha256:01b45c0191e6d66c470b6cf1b9531a771a83c1c4208272ead47a3ae4f2f603bf",
                "sha256:0283c35a6a9fbf047493e3a0ce8d79ef5030852c51e9d911a27badfde0605293",
                "sha256:055d937d65826939cb044fc8c9b08889e8c743fdc6a32b33e2390f66013e449b",
                "sha256:07751360502caac1c067a8132d150cf3d61339af5691fe9e87803040dbc5db57",
                "sha256:0b4624f379dab24d3725ffde76559cff63d9ec94e1736b556dacdfebe5ab6d4b",
                "sha256:0ce82d761c532fe4ec3f87fc45688bdd3a4c1dc5e0b4a19814b9009a29baefd4",
                "sha256:1e4747bc279b4f613a09eb64bba2ba602d8a6664c6ce6396a4d0cd413a50ce07",
                "sha256:213c60cd50106436cc818accf5baa1aba61c0189ff610f64f4a3e8c6726218ba",
                "sha256:231710d57adfd809ef5d34183b8ed1eeae3f76459c18fb4a0b373ad56bedcdd9",
                "sha256:277a0ef2981ca40581a47093e9e2d13b3f1fbbeffae064c1d21bfceba2030287",
                "sha256:2cd5df3de48857ed0544b34e2d40e9fac445930039f3cfe4bcc592a1f836d513",
                "sha256:40527857252b61eacd1d9af500c3337ba8deb8fc298940291486c465c8b46ec0",
                "sha256:432557aa2c09802be39460360ddffd48156e30721f5e8d917f01d31694216782",
                "sha256:473f9edb243cb1935ab5a084eb238d842fb8f404ed2193a915d1784b5a6b5fc0",
                "sha256:48c346915c114f5fdb3ead70312bd042a953a8ce5c7106d5bfb1a5254e47da92",
                "sha256:50602afada6d6cbfad699b0c7bb50d5ccffa7e46a3d738092afddc1f9758427f",
                "sha256:68fb519c14306fec9720a2a5b45bc9f0c8d1b9c72adf45c37baedfcd949c35a2",
                "sha256:77f396e6ef4c73fdc33a9157446466f1cff553d979bd00ecb64385760c6babdc",
                "sha256:81957921f441d50af23654aa6c5e5eaf9b06aba7f0a19c18a538dc7ef291c5a1",
                "sha256:819b3830a1543db06c4d4b865e70ded25be52a2e0631ccd2f6a47a2822f2fd7c",
                "sha256:897b80890765f037df3403d22bab41627ca8811ae55e9a722fd0392850ec4d86",
                "sha256:98c4d36e99714e55cfbaaee6dd5badbc9a1ec339ebfc3b1f52e293aee6bb71a4",
                "sha256:9df7ed3b3d2e0ecfe09e14741b857df43adb5a3ddadc919a2d94fbdf78fea53c",
                "sha256:9fa600030013c4de8165339db93d182b9431076eb98eb40ee068700c9c813e34",
                "sha256:a80a78046a72361de73f8f395f1f1e49f956c6be882eed58505a15f3e430962b",
                "sha256:afa17f5bc4d1b10afd4466fd3a44dc0e245382deca5b3c353d8b757f9e3ecb8d",
                "sha256:b3d267842bf12586ba6c734f89d1f5b871df0273157918b0ccefa29deb05c21c",
                "sha256:b5b9eccad747aabaaffbc6064800670f0c297e52c12754eb1d976c57e4f74dcb",
                "sha256:bfaef573a63ba8923503d27530362590ff4f576c626d86a9fed95822a8255fd7",
                "sha256:c5687b8d43cf58545ade1fe3e055f70eac7a5a1a0bf42824308d868289a95737",
                "sha256:cba8c411ef271aa037d7357a2bc8f9ee8b58b9965831d9e51baf703280dc73d3",
                "sha256:d15a181d1ecd0d4270dc32edb46f7cb7733c7c508857278d3d378d14d606db2d",
                "sha256:d4b0ba9512519522b118090257be113b9468d804b19d63c71dbcf4a48fa32358",
                "sha256:d4db7c7aef085872ef65a8fd7d6d09a14ae91f691dec3e87ee5ee0539d516f53",
                "sha256:d4eccecf9adf6fbcc6861a38015c2a64f38b9d94838ac1810a9023a0609e1b78",
                "sha256:d67d839ede4ed1b28a4e8909735fc992a923cdb84e618544973d7dfc71540803",
                "sha256:daf496c58a8c52083df09b80c860005194014c3698698d1a57cbcfa182142a3a",
                "sha256:dbad0e9d368bb989f4515da330b88a057617d16b6a8245084f1b05400f24609f",
                "sha256:e61ceaab6f49fb8bdfaa0f92c4b57bcfbea54c09277b1b4f7ac376bfb7a7c174",
                "sha256:f84fbc98b019fef2ee9a1cb3ce93e3187a6df0b2538a651bfb890254ba9f90b5"
            ],
            "index": "pypi",
            "version": "==6.0"
        },
        "requests": {
            "hashes": [
                "sha256:7c5599b102feddaa661c826c56ab4fee28bfd17f5abca1ebbe3e7f19d7c97983",
                "sha256:8fefa2a1a1365bf5520aac41836fbee479da67864514bdb821f31ce07ce65349"
            ],
            "index": "pypi",
            "version": "==2.28.1"
        },
        "requests-cache": {
            "hashes": [
                "sha256:3f57badcd8406ecda7f8eaa8145afd0b180c5ae4ff05165a2c4d40f3dc88a6e5",
                "sha256:b7c26ea98143bac7058fad6e773d56c3442eabc0da9ea7480af5edfc134ff515"
            ],
            "index": "pypi",
            "version": "==0.9.7"
        },
        "requests-oauthlib": {
            "hashes": [
                "sha256:2577c501a2fb8d05a304c09d090d6e47c306fef15809d102b327cf8364bddab5",
                "sha256:75beac4a47881eeb94d5ea5d6ad31ef88856affe2332b9aafb52c6452ccf0d7a"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "version": "==1.3.1"
        },
        "rich": {
            "hashes": [
                "sha256:a4eb26484f2c82589bd9a17c73d32a010b1e29d89f1604cd9bf3a2097b81bb5e",
                "sha256:ba3a3775974105c221d31141f2c116f4fd65c5ceb0698657a11e9f295ec93fd0"
            ],
            "index": "pypi",
            "version": "==12.6.0"
        },
        "six": {
            "hashes": [
                "sha256:1e61c37477a1626458e36f7b1d82aa5c9b094fa4802892072e49de9c60c4c926",
                "sha256:8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "version": "==1.16.0"
        },
        "tqdm": {
            "hashes": [
                "sha256:5f4f682a004951c1b450bc753c710e9280c5746ce6ffedee253ddbcbf54cf1e4",
                "sha256:6fee160d6ffcd1b1c68c65f14c829c22832bc401726335ce92c52d395944a6a1"
            ],
            "index": "pypi",
            "version": "==4.64.1"
        },
        "url-normalize": {
            "hashes": [
                "sha256:d23d3a070ac52a67b83a1c59a0e68f8608d1cd538783b401bc9de2c0fac999b2",
                "sha256:ec3c301f04e5bb676d333a7fa162fa977ad2ca04b7e652bfc9fac4e405728eed"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4, 3.5'",
            "version": "==1.4.3"
        },
        "urllib3": {
            "hashes": [
                "sha256:3fa96cf423e6987997fc326ae8df396db2a8b7c667747d47ddd8ecba91f4a74e",
                "sha256:b930dd878d5a8afb066a637fbb35144fe7901e3b209d1cd4f524bd0e9deee997"
            ],
            "index": "pypi",
            "version": "==1.26.12"
        },
        "wcwidth": {
            "hashes": [
                "sha256:beb4802a9cebb9144e99086eff703a642a13d6a0052920003a230f3294bbe784",
                "sha256:c4d647b99872929fdb7bdcaa4fbe7f01413ed3d98077df798530e5b04f116c83"
            ],
            "version": "==0.2.5"
        },
        "websocket-client": {
            "hashes": [
                "sha256:d6b06432f184438d99ac1f456eaf22fe1ade524c3dd16e661142dc54e9cba574",
                "sha256:d6e8f90ca8e2dd4e8027c4561adeb9456b54044312dba655e7cae652ceb9ae59"
            ],
            "index": "pypi",
            "version": "==1.4.2"
        },
        "wrapt": {
            "hashes": [
                "sha256:00b6d4ea20a906c0ca56d84f93065b398ab74b927a7a3dbd470f6fc503f95dc3",
                "sha256:01c205616a89d09827986bc4e859bcabd64f5a0662a7fe95e0d359424e0e071b",
                "sha256:02b41b633c6261feff8ddd8d11c711df6842aba629fdd3da10249a53211a72c4",
                "sha256:07f7a7d0f388028b2df1d916e94bbb40624c59b48ecc6cbc232546706fac74c2",
                "sha256:11871514607b15cfeb87c547a49bca19fde402f32e2b1c24a632506c0a756656",
                "sha256:1b376b3f4896e7930f1f772ac4b064ac12598d1c38d04907e696cc4d794b43d3",
                "sha256:21ac0156c4b089b330b7666db40feee30a5d52634cc4560e1905d6529a3897ff",
                "sha256:257fd78c513e0fb5cdbe058c27a0624c9884e735bbd131935fd49e9fe719d310",
                "sha256:2b39d38039a1fdad98c87279b48bc5dce2c0ca0d73483b12cb72aa9609278e8a",
                "sha256:2cf71233a0ed05ccdabe209c606fe0bac7379fdcf687f39b944420d2a09fdb57",
                "sha256:2fe803deacd09a233e4762a1adcea5db5d31e6be577a43352936179d14d90069",
                "sha256:3232822c7d98d23895ccc443bbdf57c7412c5a65996c30442ebe6ed3df335383",
                "sha256:34aa51c45f28ba7f12accd624225e2b1e5a3a45206aa191f6f9aac931d9d56fe",
                "sha256:36f582d0c6bc99d5f39cd3ac2a9062e57f3cf606ade29a0a0d6b323462f4dd87",
                "sha256:380a85cf89e0e69b7cfbe2ea9f765f004ff419f34194018a6827ac0e3edfed4d",
                "sha256:40e7bc81c9e2b2734ea4bc1aceb8a8f0ceaac7c5299bc5d69e37c44d9081d43b",
                "sha256:43ca3bbbe97af00f49efb06e352eae40434ca9d915906f77def219b88e85d907",
                "sha256:4fcc4649dc762cddacd193e6b55bc02edca674067f5f98166d7713b193932b7f",
                "sha256:5a0f54ce2c092aaf439813735584b9537cad479575a09892b8352fea5e988dc0",
                "sha256:5a9a0d155deafd9448baff28c08e150d9b24ff010e899311ddd63c45c2445e28",
                "sha256:5b02d65b9ccf0ef6c34cba6cf5bf2aab1bb2f49c6090bafeecc9cd81ad4ea1c1",
                "sha256:60db23fa423575eeb65ea430cee741acb7c26a1365d103f7b0f6ec412b893853",
                "sha256:642c2e7a804fcf18c222e1060df25fc210b9c58db7c91416fb055897fc27e8cc",
                "sha256:6a9a25751acb379b466ff6be78a315e2b439d4c94c1e99cb7266d40a537995d3",
                "sha256:6b1a564e6cb69922c7fe3a678b9f9a3c54e72b469875aa8018f18b4d1dd1adf3",
                "sha256:6d323e1554b3d22cfc03cd3243b5bb815a51f5249fdcbb86fda4bf62bab9e164",
                "sha256:6e743de5e9c3d1b7185870f480587b75b1cb604832e380d64f9504a0535912d1",
                "sha256:709fe01086a55cf79d20f741f39325018f4df051ef39fe921b1ebe780a66184c",
                "sha256:7b7c050ae976e286906dd3f26009e117eb000fb2cf3533398c5ad9ccc86867b1",
                "sha256:7d2872609603cb35ca513d7404a94d6d608fc13211563571117046c9d2bcc3d7",
                "sha256:7ef58fb89674095bfc57c4069e95d7a31cfdc0939e2a579882ac7d55aadfd2a1",
                "sha256:80bb5c256f1415f747011dc3604b59bc1f91c6e7150bd7db03b19170ee06b320",
                "sha256:81b19725065dcb43df02b37e03278c011a09e49757287dca60c5aecdd5a0b8ed",
                "sha256:833b58d5d0b7e5b9832869f039203389ac7cbf01765639c7309fd50ef619e0b1",
                "sha256:88bd7b6bd70a5b6803c1abf6bca012f7ed963e58c68d76ee20b9d751c74a3248",
                "sha256:8ad85f7f4e20964db4daadcab70b47ab05c7c1cf2a7c1e51087bfaa83831854c",
                "sha256:8c0ce1e99116d5ab21355d8ebe53d9460366704ea38ae4d9f6933188f327b456",
                "sha256:8d649d616e5c6a678b26d15ece345354f7c2286acd6db868e65fcc5ff7c24a77",
                "sha256:903500616422a40a98a5a3c4ff4ed9d0066f3b4c951fa286018ecdf0750194ef",
                "sha256:9736af4641846491aedb3c3f56b9bc5568d92b0692303b5a305301a95dfd38b1",
                "sha256:988635d122aaf2bdcef9e795435662bcd65b02f4f4c1ae37fbee7401c440b3a7",
                "sha256:9cca3c2cdadb362116235fdbd411735de4328c61425b0aa9f872fd76d02c4e86",
                "sha256:9e0fd32e0148dd5dea6af5fee42beb949098564cc23211a88d799e434255a1f4",
                "sha256:9f3e6f9e05148ff90002b884fbc2a86bd303ae847e472f44ecc06c2cd2fcdb2d",
                "sha256:a85d2b46be66a71bedde836d9e41859879cc54a2a04fad1191eb50c2066f6e9d",
                "sha256:a9a52172be0b5aae932bef82a79ec0a0ce87288c7d132946d645eba03f0ad8a8",
                "sha256:aa31fdcc33fef9eb2552cbcbfee7773d5a6792c137b359e82879c101e98584c5",
                "sha256:b014c23646a467558be7da3d6b9fa409b2c567d2110599b7cf9a0c5992b3b471",
                "sha256:b21bb4c09ffabfa0e85e3a6b623e19b80e7acd709b9f91452b8297ace2a8ab00",
                "sha256:b5901a312f4d14c59918c221323068fad0540e34324925c8475263841dbdfe68",
                "sha256:b9b7a708dd92306328117d8c4b62e2194d00c365f18eff11a9b53c6f923b01e3",
                "sha256:d1967f46ea8f2db647c786e78d8cc7e4313dbd1b0aca360592d8027b8508e24d",
                "sha256:d52a25136894c63de15a35bc0bdc5adb4b0e173b9c0d07a2be9d3ca64a332735",
                "sha256:d77c85fedff92cf788face9bfa3ebaa364448ebb1d765302e9af11bf449ca36d",
                "sha256:d79d7d5dc8a32b7093e81e97dad755127ff77bcc899e845f41bf71747af0c569",
                "sha256:dbcda74c67263139358f4d188ae5faae95c30929281bc6866d00573783c422b7",
                "sha256:ddaea91abf8b0d13443f6dac52e89051a5063c7d014710dcb4d4abb2ff811a59",
                "sha256:dee0ce50c6a2dd9056c20db781e9c1cfd33e77d2d569f5d1d9321c641bb903d5",
                "sha256:dee60e1de1898bde3b238f18340eec6148986da0455d8ba7848d50470a7a32fb",
                "sha256:e2f83e18fe2f4c9e7db597e988f72712c0c3676d337d8b101f6758107c42425b",
                "sha256:e3fb1677c720409d5f671e39bac6c9e0e422584e5f518bfd50aa4cbbea02433f",
                "sha256:ee2b1b1769f6707a8a445162ea16dddf74285c3964f605877a20e38545c3c462",
                "sha256:ee6acae74a2b91865910eef5e7de37dc6895ad96fa23603d1d27ea69df545015",
                "sha256:ef3f72c9666bba2bab70d2a8b79f2c6d2c1a42a7f7e2b0ec83bb2f9e383950af"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3, 3.4'",
            "version": "==1.14.1"
        }
    },
    "develop": {}
}

```
</details>

**Comment by glensc** [comment]
here's another report about output not being consistent, i.e `2022.11.23` adds space before `;`:
- https://github.com/pypa/pipenv/issues/5432#issuecomment-1325312101

**Comment by glensc** [comment]
Tried repeatedly with 2022.11.23 version, and can not reproduce. i guess it's gotten better with newer releases?

```
git clone -b 0.24.1 https://github.com/Taxel/PlexTraktSync --depth=1
cd PlexTraktSync
pipenv install pipenv==2022.11.23
git commit -am "Update pipenv==2022.11.23"
pipenv uninstall requests-cache
git commit -am 'pipenv uninstall requests-cache'
pipenv install requests-cache
git commit -am 'pipenv install requests-cache'
pipenv install requests-cache==0.9.7
git commit -am 'pipenv install requests-cache==0.9.7'
```

ps: why is `pipenv==2022.11.23` version shown as `2022.9.24`?

**Comment by matteius** [comment]
Yeah, there was a bug with that hacktoberfest PR that was corrected shortly after.

**Comment by glensc** [comment]
@matteius can you find the PR (or PRs) and refer it (them) here, or at least what version is needed?

**Comment by glensc** [comment]
and what is the final outcome that needs to be?

i still get changes like these:

```diff

-            "markers": "python_version >= '3.6'",
+            "markers": "python_full_version >= '3.6.0'",
```

```diff
+        "exceptiongroup": {
+            "hashes": [
+                "sha256:542adf9dea4055530d6e1279602fa5cb11dab2395fa650b8674eaec35fc4a828",
+                "sha256:bd14967b79cd9bdb54d97323216f8fdf533e278df937aa2a90089e7d6e06e5ec"
+            ],
+            "markers": "python_version < '3.11'",
+            "version": "==1.0.4"
+        },
```

why is that dependency added/removed?

**Comment by matteius** [comment]
The original PR to address https://github.com/pypa/pipenv/issues/5345 was https://github.com/pypa/pipenv/pull/5387
There was a followup bug: https://github.com/pypa/pipenv/issues/5395 and fix:  https://github.com/pypa/pipenv/pull/5401
I am not aware of this change having impact on markers, and there was a marker determinism issue prior that was fixed by removing `lru_cache` from requirementslib markers:  https://github.com/pypa/pipenv/pull/5373

**Comment by matteius** [comment]
@glensc -- It seems that the new version of requests-cache has an indirect dependency on `exceptiongroup` required if python < 3.11 whcih I can see is also included in their poetry lock file:  https://github.com/requests-cache/requests-cache/blob/main/poetry.lock#L128

**Comment by matteius** [comment]
@glensc Your pipenv support output shows you are on `pipenv==2022.4.8` -- I suspect the markers flipflopping is related to the prior bug I helped fix, where before they actually did that.  Can you try uninstalling pipenv multiple times and then reinstall latest from pypi?  I've seen it before where sometimes two versions get installed and you have to run `pip uninstall pipenv --yes` multiple times to get it uninstalled fully.

**Comment by glensc** [comment]
I figured U had `2022.9.24` installed via brew. i.e the version matched. not sure why or how it used  that version because `which pipenv` showed a path from venv.

**Comment by glensc** [comment]
but anyway, with 2023.11.23 I get this outcome and there's still both in the output:
- [Taxel/PlexTraktSync@`7216cea` (#1222)](https://github.com/Taxel/PlexTraktSync/pull/1222/commits/7216ceaf699f82e59d2147735a82057d0fb0ca6c)

**Comment by matteius** [comment]
Just that `python_full_version` gets used when there is a full version like `3.6.0` and `python_version` gets used when the specifier does not restrict to the full version, but rather a general version like `< 3.11`.  I think as long as the markers are generated consistently each time, it should not matter whether a marker is using python_version or python_full_version, just that it is consistent.

**Comment by glensc** [comment]
looks like problem is hit again, and it removed the "exceptiongroup" dependency. why?
- https://github.com/Taxel/PlexTraktSync/pull/1232

because dependabot runs older version?

**Comment by glensc** [comment]
> Just that `python_full_version` gets used when there is a full version like `3.6.0` and `python_version` gets used when the specifier does not restrict to the full version, but rather a general version like `< 3.11`. I think as long as the markers are generated consistently each time, it should not matter whether a marker is using python_version or python_full_version, just that it is deterministic.

okay, but how did 3.6 become 3.6.0 if package version is still same, i.e "2.1.1":
- https://github.com/Taxel/PlexTraktSync/commit/2872b5984fa9a907d2562e1fbbb66caee4a2b380

**Comment by glensc** [comment]
And also, version marker being replaced with "index": "pypi" is same bug or a new bug?
- https://github.com/dependabot/dependabot-core/issues/6091#issuecomment-1361278258

**Comment by matteius** [comment]
@koleror dependabot is still using old pipenv I believe.

**Comment by koleror** [comment]
Sad but ok 👌 
Thanks!
Nothing I can do about it I guess?

**Comment by matteius** [comment]
@koleror there have been recent efforts to upgrade dependabot's version of pipenv -- I am not sure where they are at with it currently, but it would be worth checking around their PR/s and backlog, here is a starting point:  https://github.com/dependabot/dependabot-core/pull/7922

**Comment by glensc** [comment]
https://github.com/dependabot/dependabot-core/pull/7922 is merged now
